### ISSUE TITLE
RedirectorPage uses 301 Moved Permanently

### ISSUE THREAD

**Issue by mikg0** [silverstripe/silverstripe-cms#1061]
The default redirect status code issued by a RedirectorPage is 301, which means Moved Permanently, and is as such cached indefinitely by several modern browsers.
A change of target in the RedirectorPage is thus not noticed by website visitors until their cache is emptied manually or their disk is full.

To fulfill its function as implied by the user interface (you can change the target and the website visitor will be redirected to the new target), the RedirectorPage should use a code of 307 or 302.

Edit: After a short test with a modified RedirectorPage, I found that such a modification breaks normal behaviour for sites that require a login. So I just extended the class with a new one that redirects with the code of my choice to use it for my normal redirects.

**Comment by patricknelson** [comment]
To me, I think it makes a lot of sense to allow the user to select the type of redirect that is performed, due to the major impacts it has on both SEO but also on caching. I think it would be fantastic to implement a simple set of radio buttons to allow the user to select the redirect type with I think only these two options (with 301 continuing to be the default):

* Permanent Redirect
* Temporary Redirect 

And then placing a new below this to explain why either option could be used, e.g. `Permanent redirects are useful for caching and search engines purposes. Use a temporary redirect if you still want the current URL to be available for use in the future.`

**Comment by chillu** [comment]
Some googling around suggests that HTTP cache control triggers browsers to re-request 301s (e.g. https://www.drupal.org/node/1392974). Would somebody be able to investigate further regarding browser support?

I'm not so eager to put the choice to the user, because you're basically asking them to predict the future ("only set permanent if you NEVER expect to change"). My understanding of the SEO impact of a temporary 302 is that it splits the Google rating between the original and target page rather than passing it all to the target, so not a great default.

**Comment by dhensby** [comment]
Is this being looked into?

**Comment by patricknelson** [comment]
To me I think the only complication comes in when you're not specific enough with cache control headers. Different browsers treat the lack of cache control headers differently. So, I think it would be a good idea to ensure that when we need to send a 301 redirect that you ensure you include cache control headers indicating some reasonable expiry which I think should be configured via the CMS as well.  Once you've included those cache control headers, there's no logical reason why the browser would not follow them.

Therefore, if you give the user the option to choose whether they want a 301 vs 302 redirect,  you don't necessarily lose out in terms of the permanence of that choice. Simply return caching headers and you benefit from SEO while still having choice. 

 I am not at a computer right now so I will need to take a look at the headers that are currently being sent for this page type. However if indeed these redirects are being cached permanently as @mikg0 claims, then these headers must already be actively unset (PHP defaults to sending no-cache headers).

**Comment by dhensby** [comment]
I think this is being approached from a developer's point of view - how many CMS users are going to know what the different 30x codes mean, what the impact of them will be and so on?

They setting cache control in the CMS? This is just a complication that is unnecessary for almost everyone.

The approach here needs to be allow `RedirectorPage` to be extensible in a way that a dev can change these "defaults" if needed, can add these options via a `DataExtension` and that's it. Otherwise we take on the overhead of maintenance and documentation (including user documentation) of this feature that makes the CMS experience more complex instead of simple.

**Comment by patricknelson** [comment]
Well, clearly the difference is important :smile: Being developers, it's our responsibility to train people (who are trainable, at least) and at the very minimum setup very good & sane defaults for those without the time or whit to think about it or care.

The cache control headers would be proactively set only behind the scenes in the `RedirectorPage` object. That *may* be exposed via the CMS if the developer chooses, I suppose, but I don't mean to suggest that should happen (sorry).

**Comment by patricknelson** [comment]
Moot point anyway @dhensby @tractorcow -- I took a moment to inspect headers and the 301 isn't cached anyway, at least not in the default PHP installation. I believe this may still be worth addressing at least by still explicitly setting those cache control headers in the controller. Either on the `RedirectorPage_Controller` itself or possibly deeper down in `Controller->redirect(...)` to help ensure in other installations where cache control headers aren't already sent by default will be still sent.

If you want to include the option to toggle between 302 or not I think is also potentially useful (caching here being more critical).

**Comment by tractorcow** [comment]
Someone needs to build a fix for this, or we'll close this and just leave it as the status-quo. Either a user-facing option, or some kind of config would be fine.

**Comment by patricknelson** [comment]
As long as it's extensible without modifying core and having two different kinds of `RedirectorPage` just to implement 302. I will say that I, for one, will not be the one implementing this (easy as it is) since I have no use for it at all. Those utilizing vanity URL's for SEO purposes might, however.
