### ISSUE TITLE
Silverstripe CMS - Create New page

### ISSUE THREAD

**Issue by sjdeere** [silverstripe/silverstripe-cms#1087]
When i go to create a page in the admin 
i click add new page
I choose  top level 
I choose type Page
I click Create button

The create button animates with a circle   ...and thats it ..it just hangs
no errors in logs
only error i can find  is a jquery error

Error: Syntax error, unrecognized expression: 

jquery.js  line 4266

Sizzle.error = function( msg ) {
    throw new Error( "Syntax error, unrecognized expression: " + msg );
};

install  via composer
version 3.1.5

**Comment by flamerohr** [comment]
This normally means that jQuery received a blank string e.g. `$(' ')` or similar, there is a fair bit of context missing to substantiate this issue, as mentioned by @sjdeere it could have been caused by your own code.

Please feel free to open this ticket again if anyone runs into this still and have a bit more info to help.
