### ISSUE TITLE
Report exports 1 column to CSV only

### ISSUE THREAD

**Issue by Matthew-Bonner** [silverstripe/silverstripe-cms#1104]
In SS2 you could set the columns you wanted to output in reports. In SS3 you can still do this but when you export the report to CSV in most cases only 1 column is exported and the data is incorrect.

This only happens in the report section of the administration area as other CSV exports are not affected by this bug.

As an example, the broken links report has the following columns:
1. Page name
2. Date last published
3. Problem type
4. URL

When you export the report to CSV the following column is exported:
1. Page name

The other 3 columns are missing.

As a quick fix I've ended up doing the following...

In /cms/code/reports/Report.php, in the method getReportField (roughly line 257), I've updated the method like so...

        $exportButton = new GridFieldExportButton('buttons-after-left');

        $gridFieldConfig = GridFieldConfig::create()->addComponents(
            new GridFieldToolbarHeader(),
            new GridFieldSortableHeader(),
            new GridFieldDataColumns(),
            new GridFieldPaginator(),
            new GridFieldButtonRow('after'),
            new GridFieldPrintButton('buttons-after-left'),
            $exportButton
        );

Then further down in the same method...

        $columns->setDisplayFields($displayFields);
        $columns->setFieldCasting($fieldCasting);
        $columns->setFieldFormatting($fieldFormatting);
        $exportButton->setExportColumns($displayFields);

And this appears to fix the issue, however I'm not sure if this is the best way to fix it, so could we discuss this.

You can use the silverstripe demo site to replicate this bug...
http://demo.silverstripe.org/Security/login?BackURL=%2Fadmin%2Fpages

**Comment by dmcb** [comment]
Digging into this, it looks like the CSV produced will use the summary fields of the data object pulled into sourceRecords, if possible. You can see that logic here: https://github.com/silverstripe/silverstripe-framework/blob/3.4/forms/gridfield/GridFieldExportButton.php#L103

Instead of altering the CMS you can override getReportField() by copying it from here https://github.com/silverstripe/silverstripe-reports/blob/master/code/Report.php#L328 and placing it in your report class, and then doing @Matthew-Bonner's fix.

**Comment by dhensby** [comment]
Reports has been pulled out into its own module, so moving this issue there
