### ISSUE TITLE
File properties: "Used On:" ist not working for UploadField

### ISSUE THREAD

**Issue by jand000** [silverstripe/silverstripe-cms#1147]
The information about how many pages use a particular file, is not working for UploadFields (neither for GridFields with files). It is always "0" in the edit panel on the page and in the files menu.
![silverstripeeditpage](https://cloud.githubusercontent.com/assets/754678/5595338/95d57572-9270-11e4-99b8-a386f06a8cc5.png)

**Comment by chillu** [comment]
This feature only tracks images inserted into the HTMLText fields of a page, not direct `Image` relationships such as has-ones managed through UploadField. Granted, this is misleading to users, since the whole point of this feature was to avoid deleting files that are still exposed to the public somehow. But in practice, its impossible to tell what's actually being used on a page because you can access any model through a combination of controller and template code. Even static analysis of template code wouldn't help there since references can be in logic branches like conditionals. 

@dhensby @willmorgan Since you seem to be working in the new year already ;) What do you think about renaming this form field label from "Used on" to "Inserted on"? That'd correlate with the "Insert Media" dialog title, and is less easy to confuse. Ideally we'd have a tooltip there as well reading "Counts all images inserted into the rich text editor".

**Comment by dhensby** [comment]
Hmm, I think if it's missing out on directly related images then this isn't very useful. 

It doesn't seem like its be too hard to scan for image relations on pages or other objects and then count the relations assigned to the image ID?

**Comment by kinglozzer** [comment]
@jand000 does this sound like what you’re experiencing? Or is it completely broken even for tracking in `HTMLEditorField`s?

I’ve had to explain this a few times to clients who wonder where their carousel image has gone after they think they’ve been told it’s not in use.

Despite how useful it would be, I’m not sure if this can work for direct relations - we’d have to iterate over an unknown amount of models checking for relations to `Image` (or just `File`? I *think* it tracks against `File`) and running database queries for each. There could be a lot of queries there: I’ve done something vaguely similar before in `AssetAdmin` and it significantly impacted load times in the CMS. We’d also have to change the wording because of the reasons @chillu mentioned (“pages” could become misleading), perhaps “Used in X relations” or “Used on X objects/pages”?

If we could and did decide to track direct relations, would we have to make it “opt out”? I’m trying to think of a scenario where you wouldn’t want a DataObject -> Image relation counted (I can’t think of one atm, but it might exist).

I think updating the label and adding a tooltip may help a little, but it’s still confusing (and not as helpful as it could be) for CMS users. Does anyone know if/how other CMSs deal with this?

**Comment by dhensby** [comment]
If the purpose of this is to indicate to the user whether a file can be deleted or not (due to being used on a page) then it's not doing it's job and it's no more helpful to make it more specifically about being directly embedded in the `Content` field.

Yes, we'd have to iterate over the relations, but this could be cached. We could even do it so it was a static count where an 'on relation save' hook for File could simply increment that counter (and decrement on detach). The issue there is that those hooks don't exist (yet).

If iterating over the models is a big resource hog, it could be added to the manifest to allow look ups of relations by type so it wouldn't need massive iterations at run time.

**Comment by chillu** [comment]
Yeah, as Loz points out, relationships like DataObject -> Image might be displayed on a page (e.g. profile pictures of member records), or might not (e.g. a "has_many votes"). Limiting to `SiteTree` relationships would be ignoring many ways in which data can be exposed.

Also, relations still won't capture all uses. You can write a "random image of the day" logic for the template with needing any relationship to it, technically that means all images should be classified as "used" at some point. 

By the way, we have the same problem in "Dependent pages", which only tracks `[sitetree]` links in HTMLText fields, but not anything that's a relationship to other pages.

I'm tending towards removing this piece of information, but keeping the link tracking in place. Its other use (visualising broken links in the rich text editor) works as advertised.

**Comment by jand000** [comment]
@kinglozzer Just to confirm: Yes, it's exactly the thing I meant (Only images in HTMLEditorFields are counting, not in any other usages).

In general I experienced that this is an important feature, our clients keep asking for a list with unused images (especially for large sites). At the moment their asset folders are just growing bigger and bigger …

I think it would be good to remove the "Used on nn pages" feature and build a "unused images" report instead. This way the user has to wait for the list only on demand and not every time he opens an image. (Of course this doesn't solve the issue of building this list considering all relations.)

**Comment by sminnee** [comment]
Marked as a v4 bug — with the "owns" API now in existence we have a better chance of fixing this more reliably.

**Comment by tractorcow** [comment]
Remember Uploadfield was removed in ss 4; react uploadfield doesn't have this inline edit form anymore. :)

We still need to have this link tracking in core, but it won't be relevant to uploadfield anymore.
