### ISSUE TITLE
Page Number not editable in Insert Media dialog

### ISSUE THREAD

**Issue by Cheddam** [silverstripe/silverstripe-cms#1184]
When inserting media via the WYSIWYG editor, in the From the CMS tab it is impossible to edit the page number in the pagination control directly. This functionality is supported elsewhere, and if it is not intended to be editable it should not appear as a form element.

Steps to reproduce:
1. Create fresh install of Silverstripe (tested with 3.1.12)
2. Upload >5 images to the site
3. Open the Insert Media dialog, switch to the From the CMS tab and try to edit the page number. It is unselectable.

I have not been able to establish what causes this behaviour.

**Comment by dhensby** [comment]
Is this still an issue?

**Comment by clarkepaul** [comment]
Yup also issue in MASTER

**Comment by Himayu** [comment]
doesn’t seem to be an issue any more (using dev-master)

**Comment by hoKRa1** [comment]
This only appears to happen in the first page of the file selector.

**Comment by aidanator7000** [comment]
In alpha3 this bug was an easy fix - the positioning of the parent element of the input button just needed to be set to default (from absolute)

However after the upgrade of the insert media window (to use react, I think, I only started using silverstripe very recently) this issue has changed, as it is now a drop down box, and as hoKRa1 said, it only impacts the first page. However, the fix is now a little more complicated (i couldn't figure it out) s removing position: absolute on the parent element no longer works.

**Comment by clarkepaul** [comment]
I've removed this as an issue in SS4 as it seems to be resolved but remains in SS3 from what I understand.

**Comment by dhensby** [comment]
I dont think this will be fixed in 3
