### ISSUE TITLE
3.2: The new page icon "status dots", don't update after a Multi-selection action

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-cms#1226]
As well as the page status labels, 3.2 also has coloured dots over the page icons to indicate page status.

However, when a page's status is updated via the "Multi-selection" option on the main site tree screen, these new dots are not updated:

Before:
![Before](http://spdr.me/111ue+)

After Publish Action:
![](http://spdr.me/sdWV+)

After a Refresh:
![](http://spdr.me/10afB+)

**Comment by jonom** [comment]
Had a quick look at this one, the problem is that only the contents of `li > a > span.text` are updated after a batch action, but there are classes on the `li` that need to be updated as well. I could probably hack a solution to correct the dot by using a general sibling `~` css selector targeting the label instead of relying on the class on the `li` but that wouldn't fix the root problem of the node not being updated properly, so things like the rollover colour for the link would still be wrong.

**Comment by jonom** [comment]
p.s. this is a Framework issue... go figure :)

**Comment by flashbackzoo** [comment]
I've opened a pull request for this https://github.com/silverstripe/silverstripe-framework/pull/4397
