### ISSUE TITLE
ContentController::handleRequest() breaks if not passed 2nd param

### ISSUE THREAD

**Issue by christopherdarling** [silverstripe/silverstripe-cms#1232]
If ContentController::handleRequest($request) is called without passing a $model param, the default value is used (null) which causes a "Trying to get property of non-object" error here https://github.com/silverstripe/silverstripe-cms/blob/master/code/controllers/ContentController.php#L167

Adding $this->model to the if statement on https://github.com/silverstripe/silverstripe-cms/blob/master/code/controllers/ContentController.php#L163 shold prevent this

**Comment by kinglozzer** [comment]
There was some discussion about `DataModel` recently: it’s a really old class that we would probably be better off without (cc @chillu @tractorcow - I think you guys were discussing deprecating it?).

I think for this issue, we could just modify [this line](https://github.com/silverstripe/silverstripe-cms/blob/a777266e43a829435f383df2396f93e2b0fb8064/code/controllers/ContentController.php#L158) to something like:

```php
$this->setDataModel($model ? $model : DataModel::inst());
```

**Comment by dhensby** [comment]
@kinglozzer really, getDataModel should handle the instance where there is no DataModel set and we should be using a getter...

**Comment by dhensby** [comment]
related https://github.com/silverstripe/silverstripe-framework/pull/3926 ?

**Comment by maxime-rainville** [comment]
This appears to have been fixed in SS4.

Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
