### ISSUE TITLE
Tree panel in CMS no longer horizontally scrollable (regression since 3.1)

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-cms#1235]
The tree panel width was increased, but its never going to be enough to fit all possible tree depths and page title lengths. Since we don't have drag-resize on that panel, horizontal scrolling is the next best thing. That used to work in 3.1, but was removed in 3.2 or 3. Check screenshot. Agree its not pretty, but its functional: You can see the full page title, expand deeply nested trees, and see the badges on each item.

![image](https://cloud.githubusercontent.com/assets/111025/8424595/99e2e77c-1f50-11e5-9501-ff365065339a.png)

/cc @scott1702 @flashbackzoo

**Comment by torleif** [comment]
can't we have both drag resize + horizontal scrolling? even with a modestly sized website the panel cuts off the text

**Comment by chillu** [comment]
Yeah, drag resize would be neat, although its not as simple as it might sound due to the underlying layout algorithms. Probably won't be feasible to do "live", so we'll need ghosting. Overall, separate issue (harder), so I'd like to keep this issue focused on just reinstating what we had in 3.1

**Comment by jonom** [comment]
I would like to see the horizontal scrolling restored too. As part of the 'status dot' update I set a max-width on links in the tree which I think strikes a nice balance and allows you to see status labels on roll-over but requires horizontal scrolling to work properly for deep links. It means long titles in the trees occasionally get clipped but people should be using short titles here (Menu Titles) and it doesn't really matter if a bit of it is clipped, you still see enough to get the idea. Since the width of the site tree has been widened the max-width settings might need to be tweaked to get it to all align properly now.

**Comment by jonom** [comment]
Looks like it's only beyond 6 levels that links will start to be hidden without horizontal scrolling, but I can't see any reason not to restore it.

![screen shot 2015-06-30 at 3 46 36 pm](https://cloud.githubusercontent.com/assets/1079425/8443863/63b068f2-1f3f-11e5-9ba1-bbcbdec23bb0.png)

**Comment by flashbackzoo** [comment]
Yup - I'll fix this later in the week

**Comment by flashbackzoo** [comment]
I've had a look into this and think it was introduced here https://github.com/silverstripe/silverstripe-framework/commit/8ee9130bcf10339c3eed54e10aa55f297ec89efd#diff-e330359dbf2a07355eb88647c5dd13b8R553

Removing the `overflow: hidden` fixes the scrolling issue but breaks so other styles.

I've spent a couple of hours trying to create a workaround and couldn't find a way to get horizontal scrolling and the status icons working together. @jonom any idea on an approach?

**Comment by jonom** [comment]
I will aim to look at this later today. I'm sure it worked when I submitted it so hopefully there's an easy fix in there somewhere.

**Comment by jonom** [comment]
So actually I've just fired up the 3.2 branch and I think this is a non-issue. Overflow scrolling *is* still enabled. @chillu I think what you're describing is the width/character limitation introduced for labels in the site tree when viewing the compact/sidebar tree. It was [introduced to ensure the labels can always be seen on rollover](https://github.com/silverstripe/silverstripe-framework/pull/3720#issuecomment-67282388) and [approved by @clarkepaul](https://github.com/silverstripe/silverstripe-framework/pull/3720#issuecomment-69992051).

We used to be able to fit in 4 levels without scrolling, now with the extra space available we can fit in 6 - so if we feel ~20 characters aren't enough, we could increase that minimum label width so scrolling kicks in at 4 levels again. Thoughts?

**Comment by clarkepaul** [comment]
Hmm I don't think I realised that the ability to scroll the sitetree was taken away. Even though most sites wont go deeper than six levels I think we need the ability to go deeper within the smaller site tree. From what I can tell we can't have both without some js trickery (the status label on hover and site tree scroll) which would be a real shame because providing the status on hover is a really nice addition.

Correct me if I'm wrong with my understanding of how it works.

**Comment by jonom** [comment]
Hi guys, I think we just have a misunderstanding here, which a little design tweak could alleviate.

The sidebar panel that holds the side tree is still enabled to scroll overflow content when it needs to, so you can go beyond 6 levels as far as you like. I think the confusion is caused by the fact that site tree nodes now have a min and max width, and long site tree titles will be clipped in some cases. This can appear like the sidebar pane is doing the clipping, but it's actually the individual nodes.

![silverstripe_-_edit_page](https://cloud.githubusercontent.com/assets/1079425/8525880/2498a22e-23b8-11e5-9fa2-1be980ee85c0.png)
![silverstripe_-_edit_page](https://cloud.githubusercontent.com/assets/1079425/8525919/57a6a544-23b8-11e5-8962-5b3474a6f805.png)

@chillu @clarkepaul if you try adding a page at 7 levels or deeper you should see that you can scroll the sidebar to access it. Think it's a lot easier to understand what's happening here by experiencing it than trying to visualise it.

I can add a little fade effect to the end of site tree labels if you like, might help to indicate the text has been intentionally clipped?
![fade](https://cloud.githubusercontent.com/assets/1079425/8526110/7707cad4-23b9-11e5-8e97-6d77c9d3452b.png)

Also when I submitted this feature the sidebar was narrower and I chose the min/max width settings for the tree nodes based on fitting in 4 levels without the need to scroll the sidebar panel. Now that we have more space it fits 6 levels without scrolling but this is maybe excessive and it would be better to have more text characters visible in the site tree labels. Would you like me to increase the minimum width of the nodes, so that more text is shown in the nodes at deeper levels, and scrolling kicks in after 4 levels again?

**Comment by jonom** [comment]
Note to self: if updating this also remove `deletedonlive` styles as no longer applicable (replaced by `archived`).

**Comment by dhensby** [comment]
>Note to self: if updating this also remove deletedonlive styles as no longer applicable (replaced by archived) 

Remember there is still an option I'm 3.2 to bring back the old behaviour.

**Comment by jonom** [comment]
Didn't realise that.. I suspect if you restore the old behaviour though it will still use the `archived` label in the site tree? Anyway I can just leave it there for now.

**Comment by dhensby** [comment]
Hopefully it does use the old styles as it is meant to be a polyfill for people that need the old behaviour

**Comment by clarkepaul** [comment]
@jonom Ok so you cant scroll the panel itself to see the full title but nested pages are scrollable no matter how deep (although the title seems to get shorter).

How do people feel about having a nicer experience viewing the status label (but not showing the full title) in favor of viewing the whole title and scrolling to see the status label (the old way)?

I think the new version works with the title having an elipsis (text-overflow: elipsis), the fade out wouldn't work as they end at different depths and wouldn't align with the right hand side.

![pasted_image_7_07_15_12_44_pm](https://cloud.githubusercontent.com/assets/555033/8536627/f757ec02-24a7-11e5-9e1c-92f91f792bb0.png)
![pasted_image_7_07_15_12_46_pm](https://cloud.githubusercontent.com/assets/555033/8536632/fb9ad6bc-24a7-11e5-8bdc-7b5ef2d32fbf.png)

**Comment by clarkepaul** [comment]
Thought I should add a screenshot showing the benefit of the new way as well.
![pasted_image_7_07_15_1_03_pm](https://cloud.githubusercontent.com/assets/555033/8536708/e03bf184-24a8-11e5-80b5-5424ad3ecadb.png)

**Comment by jonom** [comment]
@clarkepaul I'm pretty sure I could get a faux fade out to work with a pseudo-element on each node and a gradient, but I didn't realise `text-overflow: elipsis` was a thing - that is heaps better/clearer.

Anyone reviewing this please keep in mind that it's only long titles that will get clipped, and Menu Titles shouldn't be long - so clipping shouldn't happen that often, especially if we increase the minimum width of labels as I suggested.

**Comment by chillu** [comment]
+1 for ellipsis. And yes, I didn't realise some of those UI changes were in place when opening the ticket.
There's still some edge cases on deeper nesting where you don't see a whole lot of the title, but given the increased width of the overall panel they're rare enough.

![image](https://cloud.githubusercontent.com/assets/111025/8540829/3e3f4842-24dd-11e5-9880-749c5e610581.png)

**Comment by jonom** [comment]
How's this looking:

![labels](https://cloud.githubusercontent.com/assets/1079425/8550758/7759a0c4-2487-11e5-94bb-39295a35d5b0.gif)

I increased the minimum width so scrolling kicks in one level earlier and nodes have a bit of extra room for more text. If you likey, [PR is here](https://github.com/silverstripe/silverstripe-framework/issues/4375).

**Comment by jonom** [comment]
That `Page type:Page` title/tooltip seems like a bit of a nuisance... we could remove that or change it to include the full SiteTree->Title maybe?

**Comment by SpiritLevel** [comment]
@jonom It doesn't get much nicer than that :)

**Comment by chillu** [comment]
Likey likey! Don't remove the "Page type" label, its helpful since most page types won't have their own icons. Including full title would be great. We have to be a bit careful with transferred HTML size and DOM complexity, but at least the former is a non-issue if you have gzip enabled on the server.

**Comment by jonom** [comment]
@chillu thanks for the merge. I've had a look at the tooltip, easy addition

![screen shot 2015-07-07 at 2 21 24 pm](https://cloud.githubusercontent.com/assets/1079425/8557645/7ebe6396-24b3-11e5-9280-93b550db3f36.png)

I'd like custom page types to have a friendly label, think there must be a helper function somewhere I can use to turn e.g. 'ErrorPage' in to 'Error Page', do you know where I could find that?
![screen shot 2015-07-07 at 2 22 12 pm](https://cloud.githubusercontent.com/assets/1079425/8557659/97c63c9c-24b3-11e5-97e1-78a9a741f92c.png)

**Comment by dhensby** [comment]
that's cool

**Comment by chillu** [comment]
Yeah the helper method is `i18n_singular_name()`

**Comment by jonom** [comment]
Cheers! Tooltip PR at https://github.com/silverstripe/silverstripe-framework/pull/4377

**Comment by clarkepaul** [comment]
Nice one
