### ISSUE TITLE
CMS Page Filtering Multiple Values

### ISSUE THREAD

**Issue by nglasl** [silverstripe/silverstripe-cms#1252]
I'm currently using my module to populate a **text** field with tags, and then to filter on this (with the ability to handle multiple values).

![tagging](https://raw.githubusercontent.com/nglasl/silverstripe-fusion/master/images/fusion-tagging.png)

![filtering](https://raw.githubusercontent.com/nglasl/silverstripe-fusion/master/images/fusion-filtering.png)

This works perfectly fine. However, I noticed that when you attempt to filter on multiple values, the result set will display pages that matched any one of these tag filters, rather than all of the tag filters. In other words, the filter is using **OR** rather than **AND**. I would expect the result set to only include those pages which match my filter exactly, which is the opposite to what's happening at the moment.

Is compatibility for multiple values something that could please be looked into? You can run up test cases using the following https://github.com/nglasl/silverstripe-fusion :)

**Comment by nglasl** [comment]
Would there happen to be any update on this?

**Comment by tractorcow** [comment]
I'm not really familiar with this module sorry...

I guess the code is in https://github.com/nglasl/silverstripe-fusion/blob/master/code/extensions/TaggingExtension.php#L30?

This is a third party module, so I guess I need to relegate to you in terms of expertise. ;)

Do you need to set default_search_filter_class to something that can handle conjuctive searches instead of disjunctive searches? Maybe you need to write a FusionSearchFilter to do that. :D

**Comment by tractorcow** [comment]
Yeah, it looks like it's taking default_search_filter_class from 'Text', which isn't what you really want, is it?

ExactMatchFilter::applyMany() uses whereAny(), so your subclass should extend this and use where() instead.

I'm going to close this since this is a third-party module issue... I'm happy to give advice though if you need help working through it, but I'm going to make a call that it's not a core issue for the time being (being proved wrong, I'll re-open, though :P)

**Comment by nglasl** [comment]
Thanks for the suggestions :)

I guess I'm considering this from the perspective that somebody else is likely to hit the same thing, as it's not really specific to only this module. I'm not super keen on creating a custom search filter that is only going to work for this one module. Thoughts?
