### ISSUE TITLE
BUG Archived pages can be moved in the sitetree without effect

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-cms#1257]
First reported in https://github.com/silverstripe/silverstripe-cms/issues/1237

If a page is archived (and has no live or stage table to save sort or parentID in) it should not be able to be moved in the sitetree. Restoring these pages should restore the ability to re-order and arrange them.

**Comment by SpiritLevel** [comment]
Quick thought on user experience: why not have an archived page (along with its children) moved out of the sitetree completely, into some kind of parallel "Archive sitetree" ? This would make it easier to keep the main sitetree tidy. This Archive sitetree would be kept in sync with the main sitetree in order to keep track of page dependencies. One could select the archiving by right clicking on a page name in the main sitetree and selecting a "Move to archive" menu option; this would eliminate all mention of archives from the main save and publish buttons & "More options" dropdown at the bottom. One could take a page out of archives back into the main sitetree by a similar right click "Restore from archive"...I think there should be a delete option on archives too so that deletion is possible but it must be archived first.

**Comment by tractorcow** [comment]
The problem is, if we were to restore these pages, it makes sense to know WHERE those pages will be restored to. It provides an important context.

**Comment by SpiritLevel** [comment]
A parallel site tree kept in sync with the main site tree could store any context needed for restoring pages :) Another option, instead of having a parallel site tree, would be to have a simple check box or toggle button on the main site tree to hide/display archived pages in the site tree; it might also be useful to have a similar hide/display toggle for draft pages. Then, to see the tree with only the published parts of the site, simply de-select the "show drafts" and "show archives" check boxes. Anyhow, just ideas I'm throwing out there...:)

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/4531
