### ISSUE TITLE
Module's _config.php without any whitespace characters breaking CMS ajax interactions

### ISSUE THREAD

**Issue by michalkleiner** [silverstripe/silverstripe-cms#1344]
Hi there,

I'm not yet sure what the cause of the problem could be, but the issue is that no AJAX interactions are working for me in 3.2.1 CMS when using local reverse proxy translating to different port.

The site is running locally inside the VM on port 8906. On the host machine there is Apache reverse proxy transferring local 80 to local 8906, which is mapped to Vagrant's port 80. Everything is working fine with 3.1.x version.

Update to 3.2.1 changed it, so I wonder, what is new/different in this area, what to look for. Maybe there is some additional control in the JS processing the responses?

The URL changes correctly, so when I hit refresh, the CMS view loads correctly. Anything that is not represented by a URL doesn't work (e.g. dynamic field lookups like assigning user to a group under the Security section - basically any gridfield link existing action).

Would be good if someone could point me somewhere what to try, check, change.. If I check the response in the browser console's network tab, it looks fine and is returned by the server correctly. So I suspect something in the JS processing the response.

Thanks for any pointers/help.

Michal

**Comment by michalkleiner** [comment]
Ok, so it's not the proxy causing the issue. It's not even version 3.2, I was able to recreate the problem with 3.1.16 as well.

I narrowed it down to what has changed with the version and it was one other thing - adding a module.

I found that the AJAX response was actually not exactly the same as without the module and the difference was outputting <?php at the beginning in front of the JSON data.

And that is, crazy enough, caused by not having a single white character after the opening <?php tag in the _config.php of the module.

So to replicate this issue, create new folder of any name in the website's root folder and put a _config.php file there with just <?php and nothing else. No new lines, no spaces.

**Comment by kinglozzer** [comment]
This is a PHP thing - `<?php` with no whitespace isn’t a valid opening tag so it’s just interpreted as text. For example, if you create these two files and run `test.php` you’ll get `<?php` as the output:

test.php
```php
<?php

include 'test2.php';
```

test2.php
```php
<?php
```

When we load `_config.php` files in core, we do so by using PHP’s `include`. If `include` detects a file that contains just text (which your example `_config.php` does, because `<?php` on its own isn’t valid PHP code) it just adds it as a string to the output buffer, hence why it shows up in all your responses.

I don’t think this is something that we should look to fix in core, so I’m going to close this. If you disagree, feel free to re-open :)

**Comment by michalkleiner** [comment]
Nah, fair enough. My bad as I thought it was a valid php file. Thanks for making it clear ;-)

**Comment by dhensby** [comment]
Always have your IDE add new line to end of files :)

**Comment by michalkleiner** [comment]
Got it set up. Cheers ;-)
