### ISSUE TITLE
Add "Generated" status flag to ErrorPage

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-cms#1348]
Given that `ErrorPage` pagetypes are slightly different to most pagetypes, in that when published a static file is saved into the `assets` folder, it would be useful for CMS users to know that these pages within the CMS - while published - have not had their static counterpart generated.

This can happen for example when DB dumps are taken from one env and re-imported into another.

Solutions might comprise a simple "lozenge" indicator, unique to `ErrorPage` page-types that is red in colour and reads "Not Generated" or better, a call to `requireDefaultRecords()` on `ErrorPage` that checks if a static file exists on the F/S and if not, auto-generates it.

**Comment by jonom** [comment]
Hi @phptek, thanks for your input but since this is a feature request rather than a bug we can't accept it here. You can request new features on [UserVoice](http://silverstripe.uservoice.com/forums/251266-new-features) or discuss development ideas on the core [mailing list](https://groups.google.com/forum/#!forum/silverstripe-dev). You might also like to review [this RFC on error pages](https://github.com/silverstripe/silverstripe-framework/issues/4149) and leave any relevant feedback there.

Also note that when you run a dev/build those static files should be generated if not present, which is a good idea to do whenever you migrate a site.

**Comment by camfindlay** [comment]
@phptek Russ, it would be good if you could weigh in on that error page RFC. Agree this would be a good feature.
