### ISSUE TITLE
Userhelp in 3.3 backend links to 3.2

### ISSUE THREAD

**Issue by sb-relaxt-at** [silverstripe/silverstripe-cms#1407]
The link "Help" in the left menu of the 3.3 cms backend links to the [3.2 version of the userhelp](https://userhelp.silverstripe.org/framework/en/3.2).

**Comment by dhensby** [comment]
I've patched this. in the mean time you can fix this by adding this to your `config.yml`

```yml
LeftAndMain:
  help_link: //userhelp.silverstripe.org/framework/en/3.3
```

**Comment by SpiritLevel** [comment]
@dhensby, @cam-findlay. I think there should be a single YAML file, say versions.yml, in famework/_config/ or framework/conf or framework/docs or framework/core/manifest or framework/dev,  that has a listing of all SS versions, folders, which version is stable, and which version is the current, etc. Then, CMS can grab its own version from it and use this to point to the correct online userhelp documentation. Also, doc.silverstripe.org could use versions.yml to automatically set up docsviewer to see all versions. The update tasks for doc.silverstripe.org could also use this to know which repos to download and reindex. Perhaps api.silverstripe.org could be configured by such a versions.yml file too; not sure about this. Perhaps configuration issues for all of the semver variants could be managed in versions.yml as well. Just thinking about a more general solution rather than have references to versions scattered across lots of different files...

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/issues/5131
