### ISSUE TITLE
BUG Filter tab over the content in ModelAdmins

### ISSUE THREAD

**Issue by ClemTar** [silverstripe/silverstripe-cms#1463]
Hi there,
Front end issue here:
![image](https://cloud.githubusercontent.com/assets/12903433/14842142/a39d05fa-0c98-11e6-9248-c52788936e0d.png)

It's doing that in all the modelAdmins with a filter section.

Cheers,
Clem

**Comment by kinglozzer** [comment]
@ClemTar I’ve seen this issue before when switching between 3.2 and 3.3. Try performing a flush while in the CMS and clearing your browser cache.

**Comment by stevie-mayhew** [comment]
@ClemTar I've also seen this issue occur when using one of our modules due to an incompatible `LeftAndMain` template over writing the default - check you haven't got anything incompatible in there 😄 

See https://github.com/Little-Giant/silverstripe-catalogmanager/commit/a97c4b51461be73ec0c9680f2442c41de0565667 for our problem / solution.

**Comment by tractorcow** [comment]
@ClemTar please list the modules you are including in your composer.json, so we can double check. :D

**Comment by ClemTar** [comment]
@tractorcow Hi, I found out which module was involved:         
"littlegiant/silverstripe-catalogmanager": "^2.3"

I updated it to the version 3.0 and all is working fine now. 

Thanks.
