### ISSUE TITLE
feature request: SVG previews in CMS

### ISSUE THREAD

**Issue by Friksel** [silverstripe/silverstripe-cms#1469]
SVG is being used a lot these days. In my websites I use SVG where possible. It's not easy to edit assets from within the CMS without previews of the files.
It would be great to be able to view these from inside the CMS like you can with jpg, png etc.
Will svgs by any chance be supported by ss4's new 'assets manager'?

**Comment by chillu** [comment]
Hello there! Enhancements without an owner are best discussed on the mailinglist or forums rather than our bugtracker: https://docs.silverstripe.org/en/3.3/contributing/issues_and_bugs

We're not actively planning to support this, but the SS4 designs of the new `asset-admin` module would allow for such a SVG preview to be implemented: https://projects.invisionapp.com/boards/9GX68PTXUQFH/#/1547737

If you are interested in contributing, this is your starting point: https://github.com/silverstripe/silverstripe-asset-admin/tree/master/client/src/containers/Editor

**Comment by Friksel** [comment]
Thanks for pointing that out and give some entries @chillu . I didn't know that feature requests are not to be placed here. Looking forward to the new ss4 asset-admin module!

**Comment by chillu** [comment]
No worries!

**Comment by tractorcow** [comment]
@Friksel the next step to getting SVG is to have an `Image_Backend` that supports that extension.

At the moment GD doesn't support SVG, so that's our baseline support already broken.

**Comment by tractorcow** [comment]
Also see https://github.com/tractorcow/silverstripe-framework/issues/16 for alternatives.

**Comment by Friksel** [comment]
I understand @tractorcow . Just saying: the web just moved to SVG for a great portion, so it would be great if Silverstripe could keep up with that change. But I'm sure you are aware of that. My 2 cents :) Thanks for pointing me to the alternatives
