### ISSUE TITLE
Enhancement: History section doesn't make sense

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-cms#1493]
The history section UI doesn't make sense to me. The search doesn't work, the toggle view is unrelated as well as the title "Pages", feels like development wasn't really finished here.

![pasted_image_11_05_16__4_49_pm](https://cloud.githubusercontent.com/assets/555033/15170490/659142e6-179a-11e6-9154-86cee24f14a1.png)

I put together a quick idea to give it a refresh in the UX https://invis.io/YT79NDWK6#/157419810_CMS_History1 although it is missing the comparison screen and the option to view drafts or just published versions so would need more work.

**Comment by hoKRa1** [comment]
I am not able to see the search in Chromium 55.0.2883.87 and Firefox 50.1.0. Has it been removed?


![screenshot from 2017-01-19 14-58-48](https://cloud.githubusercontent.com/assets/13618634/22090636/d5b5a2d6-de57-11e6-9d85-07058aacbd67.png)

**Comment by clarkepaul** [comment]
Between the time the screenshots have been made a bit of styling has changed with the introduction of Bootstrap. I think the whole top toolbar in that panel is hidden under the history versions as it either didn't work or was the wrong context eg. Pages title with no site tree.
The UX of this area is pretty bad in that changing to the History tab changes the content of the previous panel.

**Comment by clarkepaul** [comment]
Marking as impact high as without modifications the history area is unusable on smaller devices.

**Comment by clarkepaul** [comment]
Potential issues with current UI:
- No colour key for new/removed content
- No HTML view (would help for links, classes etc)
- No version number in the list of versions
- Actual page name is not at the top of page (Should replace "Pages")
- Do we need to keep all draft versions—perhaps just need drafts since last published?
<img width="238" alt="pasted_image_26_06_17__1_47_pm" src="https://user-images.githubusercontent.com/555033/27522224-6f907f1a-5a78-11e7-9240-3c3a6b8bb695.png">

<img width="377" alt="pasted_image_26_06_17__1_54_pm" src="https://user-images.githubusercontent.com/555033/27522192-3d076f4a-5a78-11e7-9898-4920378c54bd.png">
<img width="436" alt="pasted_image_26_06_17__1_56_pm" src="https://user-images.githubusercontent.com/555033/27522163-f6aa8b68-5a77-11e7-9382-61367bf7a175.png">
<img width="536" alt="pasted_image_26_06_17__1_46_pm" src="https://user-images.githubusercontent.com/555033/27522235-90296c32-5a78-11e7-80f6-31ab4424e9a2.png">

**Comment by jamessilverstripe** [comment]
https://invis.io/4GCC2953J#/240908389_Page_-history-_-_Desktop

**Comment by chillu** [comment]
> Marking as impact high as without modifications the history area is unusable on smaller devices.

I disagree on the impact assessment, for reasons I've discussed on https://github.com/silverstripe/silverstripe-framework/issues/1943 (and with Paul in person). Viewing the history of a page, comparing pages and reverting to an older version is a specialised use case that I don't see as a common action in a mobile phone context. We're positioning the mobile support for SS4 as "good for quick edits". The one use case that I think has merit on mobile is approving a workflow request, and quickly reviewing changes before doing so.

Also, if we're touching this area, I think we should convert it to a React-based UI and make it independant of SiteTree - this view will be just as useful for other versioned records (in a GridField context). And it should take into account ownership models of nested versioned records. @clarkepaul How do you see an author reviewing a publish action on a page which also published a few content blocks and related assets? It's kind of a mini-campaigns view, but with diffs rather than just a preview. 

I agree this section needs attention, and the new designs look awesome. But for now lets focus on fixing obvious bugs with the current implementation, and look at the redesign in the bigger picture. If the section is unuseable on mobile, then let's hide it there. I'm unsetting the milestone, but happy to review more focused bugfixes if you want to create tickets for them.

**Comment by clarkepaul** [comment]
I just want to say that even desktop users often have their browser window over half of their monitor rather than full screen. Smaller viewport doesn't alway mean mobile (mobile is the extreme). As for making this into a reusable react component... nice! 

There are two main approaches to viewing the history of components that I see. The first one is to only include the content changes on the page they live on (not practical if that component is used on multiple pages though), and the other is that all items require their own history which could be a huge piece of work. I think this needs to be raised as part of the content blocks work.

**Comment by chillu** [comment]
The ability to show history on arbitrary objects has also come up in our current [content blocks research](https://docs.google.com/document/d/1hffZFknysYi6tp55eOk4DzON4pjoEt7Xq4GGD-ZGah0/edit#)

**Comment by chillu** [comment]
I've created a higher level ticket for this to account for all kinds of versioned records: https://github.com/silverstripe/silverstripe-versioned/issues/37. This will become important in terms of content blocks, but we likely won't get around to an implementation for another couple of months. I'd expect there to be a bit of discussion and design revisions on how we want to handle nested versioned dependants, so it'll be good to start the designs earlier

**Comment by newleeland** [comment]
This may be more work on the frontend, as simply implementing an "insert X files" into the "page" may skip a couple of configurations checks selecting a single has. e.g.
* Tooltip/Alt text for accessibility
* Permissions
* Image configurations (alignment, scaling)

**Comment by chillu** [comment]
We've completely refactored this section and implemented @clarkepaul's redesign, closing.
