### ISSUE TITLE
"Archive" name change?

### ISSUE THREAD

**Issue by neilcreagh** [silverstripe/silverstripe-cms#1575]
I realise this has been discussed before (those issues are either closed or merged) but I've repeatedly had clients who forget that 'Archive' is actually removing the page. I think it's worth raising again. 

The functionality is perfect but it should be called "Remove" or "Delete". If any of my clients have an Archive News folder (or any kind of visible, searchable Archive) they end up thinking it will put the page there. 

I realise there's resistance to using "Delete" because it implies you can't get it back (although I disagree) so how about changing the title to "Remove" ?

**Comment by tractorcow** [comment]
The main resistance to delete is that the page isn't really deleted, we are only removing it from the draft and live stages. It gave the wrong impression that doing this would permanently remove this record.

I'm happy to agree with you that the current functionality could use some more clarification. If "archive" by itself isn't clear, then some other term could be chosen. "Remove" might be worth considering.

In 4.0 we also may have the ability to remove from draft only, and use a changeset to "publish" this removal, so the terminology may need to be re-worked about the same time.

@clarkepaul how do you feel about the terms?

**Comment by clarkepaul** [comment]
"Remove" sounds like a good alternative, the other word that was thought to be usable was "Trash" as on most systems trash is known to be retrievable. Would "Remove" need to be used in conjunction with the section or type label e.g. Remove page/from-tree? perhaps not but it isn't as commonly used within UI's. If "Archive" became "Removed pages" it wouldn't quite have the same ring to it (e.g. you can retrieve pages from the Removed pages area) and might be a bit harder to use icons to describe it. The concept of "Delete" still exists in other areas of the CMS so thats why we didn't go with "Trash" in the past.

I'm keen to explore the idea of using "Remove" a test it in practice perhaps, so that we make sure it works in the majority of scenarios.

**Comment by JorisDebonnet** [comment]
Files that are linked to a page/object in the CMS have options "Remove" and "Delete from files". So "Remove" sounds like a consistent wording.

**Comment by JorisDebonnet** [comment]
Also see UserVoice: 
https://silverstripe.uservoice.com/forums/251266-new-features/suggestions/11636577-rename-archive-back-to-delete

As far as I'm concerned, "Archive" is more confusing than "Delete" to the end user. If you "Archive", you expect to have an area called "Archive" where you can un-archive whatever you archived. That is not the case: when a user "archives" a page, it is effectively "gone" as far as they are concerned, without an obvious way to restore it. It does not matter what the word means to us: it matters what it means to editors. 

The button should only say "Archive" if some module or new feature is installed that allows easy restoring of archived pages. Otherwise, it really should be Delete or Remove.

**Comment by clarkepaul** [comment]
Access to the Archive was meant to be brought out of the filter area, when user testing was done the current functionality tested really badly. It was suggested to create a new action for pages which give access to the archive (a bit like how we have a "History" action for a page). This suggested change wasn't prioritised amongst all the other work unfortunately.

**Comment by tractorcow** [comment]
I guess just change it back to delete, then, since it's simplest and easiest to understand.

If it doesn't actually delete it from the history, then that's ok, as long as it deletes it from the active site, right?

**Comment by tractorcow** [comment]
Follow up at https://github.com/silverstripe/silverstripe-framework/issues/6059

**Comment by clarkepaul** [comment]
When the terms "Delete", "Archive" were tested with users with the current functionality (you can retrieve removed pages) people preferred "Archive" but they wanted to have an easier way to see the removed pages as navigating through the filter didn't make sense to then. As archive has confusion with news archives and the like that term doesn't seem be as flexible.

I suggest trying more tests but with the terms "remove" and "trash" as well. Proper access to the archived items really needs to be made for this to all work otherwise "delete" has to be the term to use.

**Comment by chillu** [comment]
FYI there's a bit more thinking around an archive view (separate from the wording issues) on https://github.com/silverstripe/silverstripe-framework/issues/6202

**Comment by chillu** [comment]
@newleeland @clarkepaul We're introducing the "Trash" terminology through the new [global archive view](https://github.com/silverstripe/silverstripe-framework/issues/6202) now, but there doesn't seem to be any design guidance on changing any of the other wording that's still geared around "archive". Even the global archive designs itself are inconsistent there, using "Trash" for the menu label, but "archive" everywhere else. Is that intentional? I'd rather change this all in one go, instead of effectively telling users "your page has been archived, now go hunt for it in a section called trash".

Personally, I think "archive" works, now that we have an actual section for it. It clearly distinguishes from "delete" which should only be used when your deleting non-versioned records that can't be retrieved later on. Mixing those terms is likely confusing: "unpublish and archive a page, restore it from the archive", vs. "unpublish and delete a page, restore it from trash", vs. "delete a member, no restore possible".

Here's a list of user-visible mentions of those terms:
- Menu label and section title on new [global archive view](https://github.com/silverstripe/silverstripe-framework/issues/6202)
- CMS action: "Unpublish and archive"
- CMS action success message: "Archived page 'My Page'"
- Confirmation alert on CMS action ("Warning: This page will be unpublished before being sent to the archive.")
- "Page Status" search field ("All pages, including archived")
- "Archive" button on versioned GridField
- "Delete" button in AssetAdmin (should be called "archive"?)
- "Date archived" and "archived by" field labels in history viewer

**Comment by clarkepaul** [comment]
Its been on our mind, thanks for the list. After seeing this list it doesn't seem to big of a context shift. In most cases those sentences would be fairly easily changed without any functional difference if we did decide on making the shift.

**Comment by chillu** [comment]
My point is that by labeling the new section "Trash" in the menu, we've effectively made parts of this decision already, and are getting into an inconsistent state. 

Options:
1. Rename section to "archive", and consistently introduce "trash" wording at a later point (if at all)
2. Keep section name as "trash", but then adjust wording on everything else
3. Keep section name as "trash", and other wording as "archive"

I'd prefer 1, I'm OK with 2, but I don't think 3 is helpful - and that's the status quo at the moment until UX makes a decision :)

**Comment by clarkepaul** [comment]
My approach to this was always going to be opt 1 as it could be done independently from the rest of the work, effectively making the name change a separate issue and decision (this issue). Where as the design for interactions should be more communicated on the other issue silverstripe/silverstripe-framework#6202
Assets never had an archive so delete was practical at the time, it would be easier to change that to archive for the time being (there be models with the term delete also?). 

If a name change to archive was done we would need to make sure that users understand when items are retrievable and when they are not, like a "user record" vs "block". This should happen through notifications etc.

**Comment by chillu** [comment]
Talked to Paul offline, we're both happy with Option 1. I'll update the [Global Archive](https://github.com/silverstripe/silverstripe-framework/issues/6202) card to reflect that.

**Comment by tractorcow** [comment]
I dislike the term "trash" at all and don't think it fits with the silverstripe versioning model. It implies a place where items go before they are permanently deleted; Nothing versioned in silverstripe is permanently deleted so it's a mis-name.

**Comment by chillu** [comment]
Yeah I think my emphasis is on the *if at all* bit of Option 1. I don't think "trash" is a useful mental model for versioned records either

**Comment by chillu** [comment]
We've completed the "archive section" work now, to be released with SS 4.3. I'm going to close this card, since we've continued using the current terminology there ("archive"), and it makes a lot more sense now that there's an actual view for it. There's no consensus on renaming to "trash", and no "owner" who would drive such a naming change consistently (Paul as our UX lead isn't convinced either), so I'm going to close this card.
