### ISSUE TITLE
Better indicator of when you're viewing the draft site

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-cms#1578]
WAS: "Unpublished pages still show when logged in"

This may be by design because it's been like this for as far as I can remember (3.1? - 3.4), but I think it's annoying, so I thought I'd raise it :)

If I go into the CMS and say "let's unpublish this page/post for now", it will still show up in the menu/list on the website because I'm still logged in. So apparently I see all "draft" pages as long as I'm logged in. That's quite confusing because I am not able to check what the site will look like to visitors unless I view it in a different browser, or log out each time. I would have expected unpublished pages to only show up when `?stage=Stage` is appended to the URL, or something like that. In fact, I see no difference between using `?stage=Stage` and not using it, at least as long as I am logged in (as Administrator). 

# PRs:

 - [x] https://github.com/silverstripe/silverstripe-framework/pull/7399
 - [x] https://github.com/silverstripe/silverstripe-versioned/pull/45
 - [x] https://github.com/silverstripe/silverstripe-admin/pull/467
 - [x] https://github.com/silverstripe/silverstripe-cms/pull/2129

**Comment by dhensby** [comment]
This issue has been raised repeatedly in many forms. In the long run I think it'd be better to use the `?stage=Stage` get var as the indicator of whether we're viewing the stage site (rather than a session as we currently do).

The user needs to switch their viewing mode to live by using the stage switcher in the bottom right of the CMS. Alternatively, using the https://github.com/jonom/silverstripe-betternavigator module might help for the short term?

**Comment by JorisDebonnet** [comment]
That does look like an interesting module! 
I don't understand what you mean by selecting the view mode though: all I see in the bottom right is the choice between the modes Edit, Preview and Split. Those all sound Draft to me :)

**Comment by dhensby** [comment]
@JorisDebonnet I'm talking about this:

![](https://dl.dropboxusercontent.com/u/3429338/Clippings/2016-08/2016-08-15_11-36-42-Qv5075exLB.png)

**Comment by JorisDebonnet** [comment]
Ah yes, right, in the preview section in the CMS. I actually never use that, prefer using the pure edit more (I think the Split view constricts the view too much, and it also causes issues with pages that redirect in the page code). Instead, I make it look as close to the end result as possible right inside the editor by applying classes to TinyMCE's body element. 

Anyway, so I guess the only required change here is to make thhat "the default" (when there is no Stage GET parameter) is that the Published site is shown, not the Draft one. Otherwise it's too cumbersome (imo) to browse through the site "as visitors will see it".

**Comment by JorisDebonnet** [comment]
I guess perhaps a session variable is used at the moment for those cases a page may be built up with asynchronously retrieved content (like iframes), or something like that. Perhaps that can largely be solved by generating/rewriting every link so that it includes stage=Stage (in that case)? Or if that doesn't suffice, perhaps by making the session variable expire after a few seconds.

**Comment by dhensby** [comment]
> Perhaps that can largely be solved by generating/rewriting every link so that it includes stage=Stage (in that case)?

Yes, that's exactly what we'd need to do, luckily PHP has a built in function to do that for us :)

**Comment by chillu** [comment]
OK, this has come up again in a security context. We need to stop showing draft content under live URLs, since SilverStripe can't fully control caching behaviour of HTTP layers. Many HTTP caches (CDNs, proxies) allow for "ignore HTTP caching headers, cache everything" settings. There's various flaws with this:

1. While SilverStripe links to draft content with `?stage=Stage`, any further clicks or XHR requests are still made in "draft mode" under the live URL
2. Any requests made to draft content will need to contain a PHP session cookie, but cookie values are often ignored in "ignore HTTP caching headers" settings in HTTP caches.
3. Many sites set `Cache-Control` headers without `Vary: Cookie`, in which case some HTTP caches can cache without adding a cookie to the cache key. Since it's such a common problem, Varnish and Incapsula ignore the lack of `Vary: Cookie` and don't cache requests with a `Cookie` header set by default.

Proposal:

1. Append `?stage=Stage` to all URLs generated through SilverStripe (e.g. `SiteTree->Link()`)
1. Amend docs to point out that any custom JS logic will need to read this parameter from `window.location` to construct further links, e.g. for XHR requests
1. For 4.x: Make session-based stage mode opt out, require the URL parameter
1. For 5.x Remove session-based stage mode, require the URL parameter (API breaking change)
1. Add a lightweight "viewing draft content" overlay to core `text/html` responses, to aid authors and developers in this mindset shift. Can be disabled and replaced with something more sophisticated like betternavigator. Needs to be hidden in the CMS split preview.

**Comment by dhensby** [comment]
what's this we have here #7399 :)

**Comment by chillu** [comment]
> though remember some CDNs will also ignore query arguments, so this doesn't 100% solve the caching layers issue

You'll have more issues than draft content when a CDN is configured like that (e.g cache nonce params on assets). Do you have an example of a CDN that has that default behaviour, and doesn't allow you to configure the inclusion of GET params in the cache key? 

There's three behaviour variations here:
1. Cached with cache key includes query string (good)
2. Cached with cache key not including query string (bad)
3. Not cached with any "dynamic content" through query strings (OK if you can opt-in)

So this would only be a problem with caches doing #2, *and* ignoring the fact that a PHP session cookie is set, or relying on a `Vary` header that doesn't include `Cookie`. I doubt that's a problem in practice. It's a bit different from asset caching, where you want caching to happen. Here we just want to prevent it from overwriting caches on the live URL.

Quick survey:
 * [CloudFront](https://aws.amazon.com/blogs/aws/amazon-cloudfront-support-for-dynamic-content/) caches with query strings by default since 2012
 * [CloudFlare](https://support.cloudflare.com/hc/en-us/articles/206776797-What-is-Query-String-Sort-) implies that it includes query strings
 * [Incapsula](https://docs.incapsula.com/Content/management-console-and-settings/caching-settings.htm#Advanced) doesn't spell it out, but we've observed that it caches based on query params
 * [Squid proxy](https://serverfault.com/questions/401201/squid-cannot-cache-static-files-with-query-string#401205) doesn't cache by default, but can be configured to
 * [Akamai](https://stackoverflow.com/questions/5411307/does-akamai-pull-from-origin-when-query-string-parameters-change-for-cached-asse#5411319) doesn't seem to cache by default, but can be configured
 * [Related SO discussion](https://stackoverflow.com/questions/7932413/does-anyone-know-of-any-issues-using-a-querystring-within-a-css-file#15795803)
 * [Related discussion on Laravel Mix](https://github.com/JeffreyWay/laravel-mix/issues/1022)

> personally I'd remove session based stage selection from 4.x as I don't see it being part of any technical API

While it's not necessarily a technical API, it's behaviour that implementations come to rely on - for example, you'll break websites that rely on XHRs including data from versioned objects. And that's not a trivial fix to project code that you can slot in alongside a 4.2 upgrade.

> How much effort would it be to have a URL such as admin/draft/[urlsegment] and have that change the stage?

I don't see a lot of value in this over `?stage=Stage`, for reasons outlined above - and it sounds like more work in core, and more things that could go wrong (base URLs etc)

> That would make caching layers much easier to handle as admin/* can be blocked from all caching much more effectively than a query string

The presence of a php session cookie is usually enough to block caching without any path-based matches.

**Comment by dhensby** [comment]
> Do you have an example of a CDN that has that default behaviour, and doesn't allow you to configure the inclusion of GET params in the cache key?

I don't think there are any that do it by default and/or can't be configured, but your comment said that there are many that allow the enabling of "cache everything" options, so I raised a point about another possible configuration.

> While it's not necessarily a technical API, it's behaviour that implementations come to rely on - for example, you'll break websites that rely on XHRs including data from versioned objects. And that's not a trivial fix to project code that you can slot in alongside a 4.2 upgrade.

good point

> The presence of a php session cookie is usually enough to block caching without any path-based matches.

don't all users that hit SS get a session cookie immediately? so disabling caching on any user with a session cookie would render all caching on edge nodes useless, right? or am I misunderstanding.

**Comment by chillu** [comment]
> don't all users that hit SS get a session cookie immediately? so disabling caching on any user with a session cookie would render all caching on edge nodes useless, right? or am I misunderstanding.

Sessions are started "lazy", when you first interact with the `Session` object (read or write). This is most commonly the case through CSRF tokens on forms. But we run many websites that never start a session unless you are logged in as an admin, in order to allow caching them. Once you have a session cookie, HTTP caches either create infinite cache keys, or stop caching - both of which amount to the same thing.

**Comment by chillu** [comment]
PRs in https://github.com/silverstripe/silverstripe-framework/pull/7399 and https://github.com/silverstripe/silverstripe-versioned/pull/45 (just realised those haven't been linked here before)
