### ISSUE TITLE
Provide a way to translate enumValue

### ISSUE THREAD

**Issue by digitall-it** [silverstripe/silverstripe-cms#1683]
`enumValues()` is a really fast scaffolding function that could be used as is, by implementing a namespace optional string for placeholder translation, check out [here](http://www.balbuss.com/translating-an-enum-dropdown/).

**Comment by chillu** [comment]
I think if you need translations, enum isn't the right field type to use - the `Enum` DBField is getting us into lots of trouble already since it's really only a concept in MySQL. We were discussing dropping support for it in the core team, and just recommending the use of `Varchar`. That's a separate discussion, but I don't want to invest more time into extending it's capabilities with translation support. /cc @dhensby
