### ISSUE TITLE
Linked page dropdown missing page icons on second load

### ISSUE THREAD

**Issue by ewweaver** [silverstripe/silverstripe-cms#1857]
Occurs in master

The second time the site tree is loaded in Linked Page dropdown on a virtual, the page icons will not display for the top 2 level pages.

Steps to reproduce:
1. Create a virtual page
2. Open the linked page dropdown and let the pages load (icons should display)
3. Search for a page and let the results load

Icons will now now only be displayed for the 3rd level pages and down.

![image](https://user-images.githubusercontent.com/19400257/27309270-24dea120-55a7-11e7-95b0-56e0510578f0.png)

**Comment by chillu** [comment]
Note that we'll eventually replace the entwine/jstree powered `TreeDropdownField` with a simplified React-based version. You can already see that in action in React-based UIs, e.g. the "insert link from page" panel. This bug is still worth fixing since we're not planning to convert all UIs to React for the initial 4.0 release, but it reduces the priority of it.

**Comment by chillu** [comment]
We've redeveloped this field for 4.0, which is due for a stable release soon - closing this. Note that in its current form, there's no icons shown - but I'm proposing to add that back: https://github.com/silverstripe/silverstripe-admin/issues/232
