### ISSUE TITLE
Redirector Page Title should have the option to use the page I'm redirecting to

### ISSUE THREAD

**Issue by mandrew** [silverstripe/silverstripe-cms#1861]
As a user of the CMS, I'm creating a Redirector Page to link to a page with the same name, and copying the title of the linked page into the Title field. If the page I link to changes name, I'll have to update this redirector page and all redirector pages which isn't fun.

It would be nice to have the option to use the name of the Redirected page, rather then forcing a user to fill in the Redirector Page title.

**Comment by chillu** [comment]
I don't know, `RedirectorPage.Title` is the default for `RedirectorPage.URLSegment` which many people use to create shorter URLs (e.g. `mysite.com/promo` to `mysite.com/shop/free-puppies-for-everyone`). Sometimes these pages are used to show up in the navigation (`ShowInMenus=1`), but even then you might want to use a different (shorter?) title. Overall, while I can see a use case for what you describe, I think it's enough of an edge case that we won't address it anytime soon - partcularly since we already have `VirtualPage` in core which has a similar scope.
