### ISSUE TITLE
SS4 TinyMCE : text not wrapping around inserted images

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/silverstripe-cms#1865]
Quick note: I couldn't get the text to wrap around images inserted into the editor. To reproduce, just insert any image, select left wrap or right wrap for placement, and type in text at various locations. I noticed this also in 3.6 but not in earlier versions (I believe in 3.2 or 3.3).

## Pull requests

(in order of dependency)

 - [ ]  https://github.com/silverstripe/silverstripe-framework/pull/7099
 - [ ]  https://github.com/silverstripe/silverstripe-admin/pull/132

**Comment by chillu** [comment]
The problem is that `TinyMCEConfig` doesn't include `themes/simple/css/editor.css`, which would then include `themes/simple/css/typography.css`. You could argue that the core CMS shouldn't rely on themes to make core features work, but in fact if you don't have the corresponding classes (e.g. `.right`) in your theme CSS, it'll just look OK in the CMS, but then break on your website.

So in fact, we need to reinstate the ability to use the themes configured in `mysite/_config.yml` as a fallback for `LeftAndMain::$admin_themes` (see https://github.com/silverstripe/silverstripe-admin/blob/master/code/LeftAndMain.php#L665). @tractorcow @sminnee thoughts?

It doesn't look like this is a [known issue](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+typography+repo%3Asilverstripe%2Fsilverstripe-framework+repo%3Asilverstripe%2Fsilverstripe-cms+repo%3Asilverstripe%2Fsilverstripe-admin+repo%3Asilverstripe%2Fsilverstripe-installer+repo%3Asilverstripe%2Fsilverstripe-asset-admin+repo%3Asilverstripe%2Fsilverstripe-versioned+repo%3Asilverstripe%2Fsilverstripe-reports+repo%3Asilverstripe%2Fsilverstripe-siteconfig+repo%3Asilverstripe%2Fsilverstripe-assets+repo%3Asilverstripe%2Fsilverstripe-campaign-admin+repo%3Asilverstripe%2Fsilverstripe-errorpage+) elsewhere.

**Comment by sminnee** [comment]
How about this?

 * The HTMLEditorConfig interface includes a setWysiwygThemes() setter 
 * TinyMCEConfig uses that setter in getEditorCSS.
 * LeftAndMain::init() calls this setter on the HTMLEditorConfig service before switching to the admin themes

**Comment by chillu** [comment]
Perfect, that'll do the job. Avoids polluting other CMS aspects with unexpected theme resource fallbacks, but keeps it auto-configured without requiring devs upgrading to SS4 to add any more config. @SpiritLevel Do you want to have a crack at this?

**Comment by tractorcow** [comment]
I also toyed around with some kind of SSViewer::get_frontend_themes() to go with ::get_themes(). It probably should be something specific to leftandmain / htmleditor though.

**Comment by tractorcow** [comment]
Other use case this is needed; Rendering email templates triggered via CMS.

**Comment by SpiritLevel** [comment]
@chillu Just saw your request now. I'll take a look but might need some help...

**Comment by SpiritLevel** [comment]
OK, I had a quick look. Ultimately, where do you want to store the styling for floating text around images ?

**Comment by chillu** [comment]
@SpiritLevel This has been widely discussed on our internal team channel as we're gearing up towards beta1. @flamerohr and @unclecheese can fill you in. Please stand down until then.

**Comment by unclecheese** [comment]
## Pull requests

(in order of dependency)

- [ ] https://github.com/silverstripe/silverstripe-framework/pull/7099
- [ ] https://github.com/silverstripe/silverstripe-admin/pull/132
