### ISSUE TITLE
Search shows "page doesn't exist" when triggered from "edit page" screen

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-cms#1925]
# Overview

The search URL needs to contain the page ID, which would replicate SS3 functionality. I actually think it's not overly useful to show search results in the tree view by default

![image](https://user-images.githubusercontent.com/111025/29434799-9756c104-83f8-11e7-8172-a14d670e38f6.png)

# Related

 * [Update CMS search functionality to match the newer UI of Files area ](https://github.com/silverstripe/silverstripe-admin/issues/173)
 * [Batch actions are not availble in search results](https://github.com/silverstripe/silverstripe-admin/issues/173)
 * [Show page search in table view only](https://github.com/silverstripe/silverstripe-cms/issues/1926)

## Pull request

 - [ ] https://github.com/silverstripe/silverstripe-cms/pull/1931

**Comment by clarkepaul** [comment]
@chillu As we discussed, we should remove the tree view of search results which one of us can add as acceptance criteria just to be clear. Maybe stating the obvious but the main downside to this is that you won't be able to compare search results, this is because when you select an item in the list view you get taken away from the search results unlike the tree search results could be kept in the smaller tree panel (this isn't to say we couldn't eventually modify the list view to be able to be read in the smaller panel).

**Comment by clarkepaul** [comment]
Sorry seen now that removing the tree view is in another story here https://github.com/silverstripe/silverstripe-cms/issues/1926

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-cms/pull/1931
