### ISSUE TITLE
SiteTree - Page 'Status' does not update after workflow events complete.

### ISSUE THREAD

**Issue by mithungc** [silverstripe/silverstripe-cms#1967]
For the pages set to 'Embargo' or 'Expire', after the scheduled publishing or un-publishing completes, the page status does not get updated on the SiteTree i.e. -

- 'Published page' still shows the status as 'Embargo'
- 'Unpublished page' still shows the status as 'Expiry'.
- For pages set to 'Embargo & Expire', though the whole event completes the status continues to show - Embargo+Expiry

Note - The 'Status' only updates on a page refresh.
Version - SS4

**Comment by dhensby** [comment]
Is this an issue with workflow module rather than CMS?

**Comment by notginga** [comment]
It's more that the page status isn't updating in the site tree when navigating around pages.  It's the same for pages that are published/unpublished or modified by another user or in another window.

**Comment by dhensby** [comment]
OK - this sounds like a CMS issue

**Comment by chillu** [comment]
>  It's the same for pages that are published/unpublished or modified by another user or in another window.

Correct, modifications from another user in another window need a page refresh to be reflected. In an ideal world, they wouldn't - but I don't consider that a bug as such. Same goes for any background activities like scheduled publishing *while* a user has the CMS open. Closing this for now, since I don't see how we can realistically action this in the next year or so - it requires fairly major changes to the CMS (websocket notifications, or a more streamlined polling model)
