### ISSUE TITLE
SS4: How To "RTL" The CMS ?

### ISSUE THREAD

**Issue by Mu9tafa-Online** [silverstripe/silverstripe-cms#2108]
I'm Building an **Arabic** Website Using SS4, and i wanna know how can i change the admin direction
To be "Right-To-Left", any Ideas ?

**Comment by chillu** [comment]
I think there's two issues here:

1. Change the text direction to right aligned. I thought this was already encoded in the Unicode characters, but apparently not (just checked it out). Might just be a matter of adding `<html dir=rtl>`? Do you want to give that a shot? Check `LeftAndMain.ss` for the main template.

This is what it looks like at the moment:

![image](https://user-images.githubusercontent.com/111025/36949878-babb051e-2052-11e8-8e11-c3bb69779584.png)

2. Change the layout, e.g. to have the menu on the right instead of the left. That's a bit harder since we need to adjust CSS. There seem to be frameworks and resources that can hep with this (http://rtlcss.com/, https://rtl-css.net/).

Overall, we'll need to rely on the community to drive this. Do you know any other SS users which would be interested in collaborating on an RTL implementation?

**Comment by tractorcow** [comment]
@Mu9tafa-Online check out the docs on i18n; There's a script helper for setting text direction. Normally this is used on the frontend, but you can customise and decorate the admin templates separately.

https://docs.silverstripe.org/en/4/developer_guides/i18n/#declaring_the_content_language_in_html

Here's a protip; If you want to create a theme that only affects admin, you can add it to the admin_themes config. :)

```yaml
name: myrtltheme
---
SilverStripe\Admin\LeftAndMain:
  admin_themes:
    '/mysite/themes/rtladmin'
```

**Comment by tractorcow** [comment]
Switching to affects/v4... we may want to support this in core at some point.

**Comment by Mu9tafa-Online** [comment]
i hope that **RTL** will get more attention, because it's really frustrating to face this exact issue now a days   - i wish i could help, trying to do my best

**Comment by Mu9tafa-Online** [comment]
Any updates on this? It's been along time since I used SilverStripe.
