### ISSUE TITLE
URLSegmentField readonly state should look like a text field

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-cms#2137]
![image](https://user-images.githubusercontent.com/5170590/38220318-b05f18ac-372d-11e8-80a0-61b2add7c5b3.png)

**SS 4.2.x-dev**

The URL segment field should look like a standard text field in its readonly state.

**Comment by dhensby** [comment]
At first I thought I agreed, but actually, if the readonly version has a similar layout (widths) then it's more instantly recognisable as a version of what they are used to. what reason in particular do you think it should be the same (width) as the text fields?

**Comment by robbieaverill** [comment]
I guess that's true. In the same respect though we should render checkboxes as checkboxes in readonly rather than text fields with 0 or 1 in them =D

This came up in a conversation with @clarkepaul so I chucked the screenshot in here

**Comment by clarkepaul** [comment]
It looks as if it has purposely been created to use the appearance of a field yet this field isn't using the right classes (as the other readonly fields). I'm presuming we use this style consistently for all different field types to purely make it easier for ourselves in the long run, rather than them all having unique readonly presentations. 

It would be weird if we make this the one thing which appears different. If it aligns style-wise with the other readonly fields then it would hopefully also get future style changes.
