### ISSUE TITLE
Please make public dir configurable

### ISSUE THREAD

**Issue by asecondwill** [silverstripe/silverstripe-cms#2148]
Having an inflexible name for the public webroot is awkward for me.  On local I have a setup where webroot is called wwwroot for all development sites. it routes automatically. 

websites/ssblog/wwwroot
websites/ss-client-project/wwwroot

It's not flexible.  I need to be able to configure the websites to fit in.

I also host on Cloudways.  They supply a handy admin layer over Digital Ocean.  They don't allow public_html to be renamed. I checked.

> Alright,  I am sorry but due to our fully automation process we can not change that

No shared hosting will allow that to be changed.  I don't really use that anymore, but some might. 

I think this could be an issue for quite a few people.

**Comment by asecondwill** [comment]
https://github.com/silverstripe/silverstripe-framework/issues/7926

that probably avoids the need, although if it was configurable we could take advantage of the feature, rather than just not using it.

**Comment by dhensby** [comment]
1. Using `public` webroot is optional
2. When using `public` webroot you can have it as a sub dir to the real webroot and a `.htaccess` rewrite can rewrite requests to `public/index.php`

I think it's unlikely this will be made flexible in 4.x but possibly in 5.x - it may need some community effort too.

**Comment by tractorcow** [comment]
Using `public` webroot will become mandatory in 5.x; sorry it's the opposite of what @dhensby suggests. ;)

We've had a huge discussion in the past about making this configurable, where I was on the side of making this an `.env` variable (`SS_PUBLIC_DIR`), but the result of this discussion was to not make it configurable.

This is because a soft-coded variable would violate the "convention over configuration" principle. For example, all of our composer plugins would need to now read `.env` variables for any projects, resulting in a few bootstrapping chicken/egg issues.

At the moment we have a couple of hard-coded hacks in these modules to account for `mysite` vs ` app` folder (another folder which will eventually become hard-coded), as well as `public` vs no-`public` dirs. 5.x will see these hacks being removed and the folders fixed in place, rather than increasing configuration (and thus complexity).

> On local I have a setup where webroot is called wwwroot for all development sites. it routes automatically.

To look at this another way, if we fix this to `public` in the future you can set your local config to use the `public` folder, and you don't need to soft-code this convention in your locale apache config either.

If you can't change that folder, then put your project inside `wwwroot` itself (i.e. with `wwwroot/public` folder) and it should still work due to the root `.htaccess` rewrite.

Even if we could make the public folder configurable, I would vote to leave it fixed.

**Comment by asecondwill** [comment]
@tractorcow  - as long as we can just ignore this and put everything in the wwwroot and rely on htaccess thats fine (as long as it's not completely insecure) but otherwise it would count SS out of a lot of projects.  We aren't going to be managing our own vps for every little brochure site with a cms behind it.  

at the moment the installer is broken when doing that.

**Comment by chillu** [comment]
What @tractorcow said. I'm sorry, if it was easy we'd do it, but this is so early in tooling (composer) and framework bootstrap that it isn't. You have a choice to continue running without `public/`, although we might need to revisit this for 4.x. For reference, the complexity involved is documented in https://github.com/silverstripe/silverstripe-framework/issues/7419

**Comment by asecondwill** [comment]
>  You have a choice to continue running without public/, although we might need to revisit this for 4.x

K,  that would be a disaster for me, but everybody has different use cases.

**Comment by chillu** [comment]
Sorry, I meant "revisit this for 5.x", which is end of the year at the earliest - with 4.x being a Long-Term-Support (LTS) release.

**Comment by purplespider** [comment]
If using `public` is going to be made compulsory at some point, an official solution for running SilverStripe on shared hosting that doesn't let you change the name of the default document root folder will need to be found.

cPanel/WHM, argubly the most common software on shared servers sets the document root to `public_html` and this cannot be changed without root access.
