### ISSUE TITLE
New Search UI for AssetAdmin

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-cms#2185]
Parent story: https://github.com/silverstripe/silverstripe-cms/issues/1777

# Acceptance Criteria

 * I can search for files and folders in AssetAdmin and the "insert media" panel
 * I can use advanced search filters
 * Closing the search bar (clicking 'x'), clears the search and returns me to the root folder view
 * I can bookmark search results in AssetAdmin

# Notes

 * Designs: https://invis.io/FTG16IYV5KB#/299750159_POC_CMS_Search_Menu_C3
 * Uses the [general purpose search component](https://github.com/silverstripe/silverstripe-cms/issues/2184)
 * Related: [New Search UI for Pages](https://github.com/silverstripe/silverstripe-cms/issues/1777)

# PR
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/812

**Comment by maxime-rainville** [comment]
I got the existing search using the new Search component. This takes care of all the acceptance criteria.

Couple points I need clarification on.
1. The search box looks a bit weird when the file info side panel is open, do we have a preference on how to address this?
2. When you're on the search results page, I've set it up so you can't _untoggled_ the search box. Is that the expected behavior?
3. The `limit search to the current` folder doesn't work on the search result page, so if you don't check it before executing your search it gets ignored. Do we want this address now, or on a separate issue?

# Weird Search box with side panel combination
![screenshot from 2018-07-19 14-12-31](https://user-images.githubusercontent.com/1168676/42917876-87f75952-8b5f-11e8-9f71-d1ce5a9cf6f0.png)

**Comment by lukereative** [comment]
@maxime-rainville Pressing clear doesn't return me to the root view at the moment, has this AC changed? Otherwise It'll need a fix.

**Comment by maxime-rainville** [comment]
I read the `clear` in the acceptance criteria as the X button. From the discussion I had on the generic search component, my understanding is that the `Clear` button removes all data from your form without doing a search.

**Comment by lukereative** [comment]
Cool I've clarified this with Jared and your assumption is right, so I've updated the AC's to better explain this.
