### ISSUE TITLE
Update CMS/PL Buttons CSS to align with buttons design

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-cms#2199]
CSS of buttons withing the CMS and Pattern Library are not consistent with design documation. This is because of several issues.
- Update to Bootstrap 4 stable, has caused some CMS bootstrap CSS commenting redundant
- SCSS Variable additions/removal/changes in BS4 Stable.

Button Designs:
https://invis.io/FMLCJNOJ8D2#/291645806_Buttons

### Related scss files
- [ ] Update bootstrap CSS with latest bootstrap on src/styles/_bootstrap-variable.scss 
```
// Buttons + Forms
//
// Shared variables that are reassigned to `$input-` and `$btn-` specific variables.

$input-btn-padding-y:         .3846rem; // 5px SS custom
$input-btn-padding-x:         .7692rem; // 10px SS custom
//$input-btn-line-height:       $line-height-base !default;

//$input-btn-focus-width:       .2rem !default;
//$input-btn-focus-color:       rgba($component-active-bg, .25) !default;
//$input-btn-focus-box-shadow:  0 0 0 $input-btn-focus-width $input-btn-focus-color !default;

$input-btn-padding-y-sm:      .231rem; // 3px SS custom
$input-btn-padding-x-sm:      .462rem; // 6px SS custom
//$input-btn-line-height-sm:    $line-height-sm !default;

$input-btn-padding-y-lg:      .462rem; // 6px SS custom
$input-btn-padding-x-lg:      .923rem; // 12px SS custom
//$input-btn-line-height-lg:    $line-height-lg !default;

//$input-btn-border-width:      $border-width !default;


// Buttons
//
// For each of Bootstrap's buttons, define text, background and border color.

// $btn-padding-y:               $input-btn-padding-y !default;
// $btn-padding-x:               $input-btn-padding-x !default;
// $btn-line-height:             $input-btn-line-height !default;

// $btn-padding-y-sm:            $input-btn-padding-y-sm !default;
// $btn-padding-x-sm:            $input-btn-padding-x-sm !default;
// $btn-line-height-sm:          $input-btn-line-height-sm !default;

// $btn-padding-y-lg:            $input-btn-padding-y-lg !default;
// $btn-padding-x-lg:            $input-btn-padding-x-lg !default;
// $btn-line-height-lg:          $input-btn-line-height-lg !default;
//
// $btn-border-width:            $input-btn-border-width !default;

//$btn-font-weight:              $font-weight-normal !default;
//$btn-box-shadow:               inset 0 1px 0 rgba($white,.15), 0 1px 1px rgba($black,.075) !default;
//$btn-focus-width:              $input-btn-focus-width !default;
//$btn-focus-box-shadow:         0 0 0 3px rgba(theme-color("primary"), .25) !default;
//$btn-disabled-opacity:         .65 !default;
//$btn-active-box-shadow:        inset 0 3px 5px rgba($black,.125) !default;

//$btn-link-disabled-color:      $gray-600 !default;

$btn-block-spacing-y:            0.615rem; // 8px SS custom
```

- [ ] Potentially removing variable src/styles/_variable.scss
```
// Buttons
//

$btn-spacing: 5px;
$btn-icon-spacing: 6px;
$btn-font-weight: normal;

$btn-primary-color: $white; // REMOVE: unnecessary code
$btn-primary-bg: $brand-success; // REMOVE: unnecessary code
$btn-primary-border: $btn-primary-bg; // REMOVE: unnecessary code
$btn-primary-shadow: darken($btn-primary-bg, 6%);

$btn-secondary-color: $text-muted; // REMOVE: unnecessary code
$btn-secondary-bg: darken($body-bg, 5); // REMOVE: unnecessary code
$btn-secondary-border: $border-color-dark;
```
- [ ] Inspect custom (hacky) code for component/FormAction/FormAction.scss 
```
// Specific button variations
.btn-primary {
  border-bottom-color: $btn-primary-shadow;

  .btn__circle {  //?????????????????? how is btn-primary using white text
    background: $white;
  }

  &:focus {
    outline-color: $brand-primary;
  }
}
```
```
.btn--icon-danger:hover::before {   //???????????????? Very unsual use of selector
  color: $brand-danger;
}
```

**Comment by robbieaverill** [comment]
Hey @newleeland 

Firstly, this issue should probably be on the silverstripe/admin repository, but it's not that important =)

>CSS of buttons withing the CMS and Pattern Library are not consistent with design documation.

Another reason is that we occasionally customise the design of CMS UI elements for specific areas. In these cases the CSS rules will be targeting specific containers, and as a result won't always be reflected in the pattern library.

I'm assuming the pattern library is using the silverstripe-admin styles and not just Bootstrap on its own.

>Update bootstrap CSS with latest bootstrap on src/styles/_bootstrap-variable.scss

I agree that this needs to be done. This is important because modules other than silverstripe/admin are not able to use Bootstrap variables that aren't defines in the admin module's variable sheet. Most of them are commented out, which works fine in admin (transparently loading from the Bootstrap default values) but doesn't work in other modules.

If we keep the physical structure of the Bootstrap stylesheet intact and simply change the values (not whitespace) then it should be easy enough to diff the two files to find out what has been changed. Alternatively we could change values and comment out the original values at the end of lines.

>Potentially removing variable src/styles/_variable.scss

We can't do this. This is the only entry point that SilverStripe modules and themes have into the CMS styles.

The lines you've commented as unnecessary are probably defined to allow them to be used in modules other than silverstripe-admin, as noted above in "Update bootstrap CSS with latest bootstrap on src/styles/_bootstrap-variable.scss"

>Inspect custom (hacky) code for component/FormAction/FormAction.scss

I'd debate that this code is hacky.

The first annotated line "how is btn-primary using white text" is actually a white _background_ rather than white text, and only applies to elements with `btn__circle` classes that are children of (inside) `btn` class elements. A quick search on the codebase shows that these are primarily used for the SilverStripe CMS loading indicators in buttons, e.g.:

![image](https://user-images.githubusercontent.com/5170590/41633227-e6a1186a-7491-11e8-880a-162b0a397fda.png)

The other comment "Very unsual use of selector" - we have two ways of adding font icons in the SilverStripe admin area. One is by applying classes like `font-icon-rocket` to elements, the other is by using the `silverstripe` font set and defining `content` rules in before and after pseudo selectors on elements. This rule applies to `btn--icon-danger` classed elements when they're hovered, and will make the font icon the same colour (danger). I realise that this selector is potentially a little difficult to read, but it's a pretty standard format.

Hope that clarifies what these custom styles are for!

**Comment by GuySartorelli** [comment]
The CMS is likely to undergo a redesign in the somewhat-near future, and we aren't likely to rework the css to match old designs in the meantime.
