### ISSUE TITLE
"Show as list" link in large site tree's doesn't work

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-cms#2210]
This is passed on feedback from someone using SilverStripe 4 site tree with large nested sites.
For pages which have a lot of children the tree shows a link "Show as list" but the link doesn't do anything or go anywhere. Its expected that the user will be taken the list view where pagination can be used to navigate through the items.

![image](https://user-images.githubusercontent.com/555033/42425553-0cecca7e-8373-11e8-8b92-13df6da1c2c0.png)

Styling could also be improved at the same time :)

I don't have a large site to confirm this issue so if someone can first confirm the issue, that would be good. The use of Lumberjack resolved the issue for the user.

 ## Pull Requests
- [ ] ~~https://github.com/silverstripe/silverstripe-cms/pull/2220~~
- [ ] ~~https://github.com/silverstripe/silverstripe-admin/pull/588~~
- [x] https://github.com/silverstripe/silverstripe-admin/pull/600
- [x] https://github.com/silverstripe/silverstripe-cms/pull/2232

**Comment by maxime-rainville** [comment]
I just tested it locally on SS4X and got the same issue. I'll have a quick look. Can't image it's that difficult to fix.

**Comment by maxime-rainville** [comment]
Did I imply this would be easy? Foolish me!

I think I found the bit of code that's suppose to handle this link. It doesn't look like it's ever called however.

https://github.com/silverstripe/silverstripe-cms/blob/d1112f25b944d94535532753ea08d07192af6f76/client/src/legacy/CMSMain.Tree.js#L56-L69

`CMSMain.Tree` extends `LeftAndMain.Tree` which calls `jquery.jstree` with the results of the `getTreeConfig()` method. I'm pretty sure the problem is somewhere in `jquery.jstree`.

**Comment by clarkepaul** [comment]
Thanks for investigating

**Comment by maxime-rainville** [comment]
Was fix on the 4.1 branch.
