### ISSUE TITLE
Link tracking adds extra tab to CMS edit form

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-cms#2227]
4.2.0+

For DataObjects with a direct relation to a file, an extra tab is added called “LinkTracking”. `SiteTreeLinkTracking` should remove it with

```php
/**
 * @param FieldList $fields
 */
public function updateCMSFields(FieldList $fields)
{
    $fields->removeByName('LinkTracking');
}
```

### PR's
* [x] https://github.com/silverstripe/silverstripe-cms/pull/2247
* [x] https://github.com/silverstripe/silverstripe-framework/pull/8353

### Related Issues
* https://github.com/silverstripe/silverstripe-assets/issues/156

**Comment by chillu** [comment]
I'm going to classify this as `impact/high` since we now have link tracking on things like "Member", without this object having *any* links to track by default. This is cluttering the UI and making it highly confusing.

**Comment by chillu** [comment]
Talked with @lukereative @unclecheese and @maxime-rainville, we all agree that this tab should be opt-in to avoid that confusion. Files and images are an exception, but they also have a specialised "used by" view.

**Comment by maxime-rainville** [comment]
1. I was telling you porkies ... You can define a config flag on the `DataExtension` and than override it on the specific class that the extension is applied to. Just make sure you fetch the config value through the `owner`. If the only thing this flag does is hide/show the link tracking tab, I might call `show_link_tracking`. `has` implied that it will alter how data will be handled in the background.
2. There's probably other objects that will need that flag set to true. Image/File, maybe Elemental data blocks. Remember that there's nothing stopping someone from sticking Files and Images in a GridField rather than managing them through asset-admin. I would expect them to behave c
3. Good
4. I just trying to think of the best place to document this. Maybe the [Relationship between Records](https://docs.silverstripe.org/en/4/developer_guides/model/relations/) or a brand new wider article about link tracking.

Don't forget to make sure the Used on field in asset admin still works afterwards.

**Comment by chillu** [comment]
+1 on `show_link_tracking` approach

**Comment by kinglozzer** [comment]
I like that approach, could we adopt it for file tracking too? https://github.com/silverstripe/silverstripe-assets/issues/156

**Comment by chillu** [comment]
Good point, since you define this per `DataObject`, we should probably rename the implementation above to `show_sitetree_link_tracking` and add functionality for `show_file_link_tracking`? /cc @bergice
