### ISSUE TITLE
HTML editor in-page links breaking without user changes

### ISSUE THREAD

**Issue by fingermonster** [silverstripe/silverstripe-cms#2256]
Last week I found previously working in-page links in one of our sites were broken. These were a mix of external and internal sitetree links.

Logging into the CMS, sitetree indicated most pages bizarrely had outstanding changes in draft.  Affected pages hadn't been edited in months.

On inspection, the start of the broken links had all been appended with [sitetree_link,id=] regardless of them being internal or external links.

External links also had multiple instances of http://.

I manually deleted/re-added hundreds of links and republished the pages, and the links worked.

Checking the site today a week later, a number of pages have gone back to draft and the previously corrected links changed in the same way - e.g. [sitetree_link,id=]http://www.externalexample.com/

Version history shows affected pages edited by author "Unknown" two days ago.

Taking an educated guess, this has occured since 3.7 as 

CMS version 3.7.1, PHP 7.1, MariaDB 10.1.35.

**Comment by robbieaverill** [comment]
Can you share your composer.json file please?

**Comment by fingermonster** [comment]
{
	"name": "silverstripe/installer",
	"description": "The SilverStripe Framework Installer",
	"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/fingermonster/DataObject-as-Page"
        },
        {
            "type": "vcs",
            "url": "https://github.com/symbiote/silverstripe-gridfieldextensions"
        }
    ],
	"require": {
		"php": ">=5.3.3",
		"silverstripe/cms": "3.*",
		"silverstripe/framework": "3.*@stable",
		"silverstripe/reports": "3.*",
		"silverstripe/siteconfig": "3.*",
		"silverstripe/userforms": "4.2.*@stable",
		"silverstripe/googlesitemaps": "@stable",
		"kinglozzer/metatitle": "^1.0",
		"silverstripe/secureassets": "@stable",
		"i-lateral/silverstripe-custommenus": "*",
		"arambalakjian/DataObjectasPage": "dev-master",
		"silverstripers/googleanalytics": "dev-master",
		"undefinedoffset/sortablegridfield": "^0.6.9",
		"silverstripe/spamprotection": "@stable",
		"studiobonito/silverstripe-spamprotection-honeypot": "dev-master",
		"symbiote/silverstripe-gridfieldextensions": "@stable",
		"azt3k/abc-silverstripe-mailer": "dev-master"
	},
	
		"replace": {
		"silverstripe-australia/gridfieldextensions": "*"
	},

	"require-dev": {
		"phpunit/PHPUnit": "~3.7"
	},
	"extra": {
		"branch-alias": {
			"3.x-dev": "3.3.x-dev"
		}
	},
	"config": {
		"process-timeout": 600
	}
}

**Comment by fingermonster** [comment]
I've got a site full of broken links again after no changes have been made for weeks.
Any thoughts on the cause of this issue would be greatly appreciated.

**Comment by kinglozzer** [comment]
@fingermonster I’m going to close this, because 3.x is now only receiving critical/security fixes, plus if this were a bug in a core module then we would’ve had _a lot_ of reports about it.

I would start by inspecting the `SiteTree` table to see which pages have recently been updated (the `LastEdited` value) and try to work from there. The “Unknown” user in the page history suggests to me that something is programatically making changes, with the “unknown” signifying that there’s no user currently logged in. Perhaps some code is triggering a `write()` when a user on the front-end performs an action? Or a command line task/build task?

For support, I’d recommend our [forums](http://www.silverstripe.org/community/forums/) and [Slack](https://silverstripe-users.signup.team/). Good luck!
