### ISSUE TITLE
Breadcrumbs should use "navigation label" not "page title"

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/silverstripe-cms#2267]
As titled and shown:

![image](https://user-images.githubusercontent.com/3260989/45659751-0de6be80-bb4a-11e8-8f90-fa20f8d41c17.png)
![image](https://user-images.githubusercontent.com/3260989/45659764-1a6b1700-bb4a-11e8-9410-762b483a4d1c.png)

It makes sense to use the navigation label for a navigation control like breadcrumbs.

Raised in a CMS author training.

**Comment by clarkepaul** [comment]
Is this perhaps a theme thing, or is it default output of breadcrumbs?

**Comment by kinglozzer** [comment]
Looks like this is a theme thing - the default breadcrumbs template uses `$MenuTitle` https://github.com/silverstripe/silverstripe-cms/blob/4.2.1/templates/BreadcrumbsTemplate.ss

**Comment by ScopeyNZ** [comment]
I checked that and didn't think my installation was using a theme. I will recheck in the morning though.

**Comment by robbieaverill** [comment]
Looks like you're using the starter theme: https://github.com/silverstripe/cwp-starter-theme/blob/master/templates/BreadcrumbsTemplate.ss#L11-L15

While the code looks deliberate, I suspect that the purpose was to omit the anchor tag in the last item in the list, rather than to use a different attribute for it

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/cwp-starter-theme/pull/61, since this is a theme bug I'm going to close this issue now
