### ISSUE TITLE
RFC: deprecate special lumberjack::stageChildren features

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-cms#2270]

**Comment by chillu** [comment]
@sminnee There's a couple of filters in `Lumberjack->stageChildren()` (https://github.com/silverstripe/silverstripe-lumberjack/blob/master/src/Model/Lumberjack.php#L79) - which ones do you mean?
 
 * Hide certain page types in CMS tree. This has some UX merits, since it allows the implementation to tell the author to use the main edit form for detail management. It relies on the area enforcing to only create items of this type though, otherwise you get weird partial trees. I don't think it has much merit for performance, since we should have a system which works well without these limited opt-ins.
 * Hide certain page types in hierarchy. Presumably this is used for menus outside of the CMS? I think it should be covered by `ShowInMenus`
 * Hide pages with `ShowInMenus=1`. Same concern about partial trees. It also means state management gets more complex, we'd need to refresh the tree when you change the setting on a specific page.

**Comment by sminnee** [comment]
OK so Hierarchy::stageChildren() implements these all already with different names, so we probably just need to deprecate these configuration options, and eventually delete Lumberjack::stageChildren() altogether.

> Hide certain page types in CMS tree

Covered by Hierarchy.hide_from_cms_tree

> Hide certain page types in CMS tree

Covered by Hierarchy.hide_from_hierarchy

> Hide pages with ShowInMenus=1. 

Provided on any object that has a ShowInMenus fields, if the first boolean argument to stageChildren ($showAll) is false.

https://github.com/silverstripe/silverstripe-framework/blob/4/src/ORM/Hierarchy/Hierarchy.php#L420

**Comment by sminnee** [comment]
This has been covered in this lumberjack ticket: https://github.com/silverstripe/silverstripe-lumberjack/issues/86

**Comment by sminnee** [comment]
The lumberjack ticket covers everything that needs to be done, so closing this one.

**Comment by chillu** [comment]
OK, looks like more copy paste than I expected heh - should've checked back with `Hierarchy`. Thanks for digging through this!
