### ISSUE TITLE
UX BUG: it is incredibly hard to see what page is selected in Site Tree

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-cms#2360]
## Affected Version

SS4.3

## Description

Can you see what page is currently being edited in the SiteTree?  The highlighting is inadequate.  It may be visible on a fancy new Mac, but on my ASUS I have to really look very hard to see it:

![image](https://user-images.githubusercontent.com/167154/50961123-d8684580-152b-11e9-9cf7-d75af3fcce34.png)

## Steps to Reproduce

Open any site

## Implementation ACs
- Retain two selected colour states. 
- New colours are in the SilverStripe internal DSM.

# Pull Requests
- [x] https://github.com/silverstripe/silverstripe-admin/pull/946

**Comment by clarkepaul** [comment]
@sunnysideup I agree with you, those colours are still from SS3 are need adjusting. I am pushing for  more UX issues to be done but there is only so much I can get prioritised unfortunately. For this particular issue I can provide the design if someone from the community wants to pick it up. Otherwise it will need to go into the priority list unfortunately. We would need to go lighter with the background colour as we need contrast with the text and it only passes, we are currently [swapping out the page tree icons](https://github.com/silverstripe/silverstripe-admin/issues/574) for font icons so we might be able go dark blue for selected once thats done (trying to get that in before the next point release). 

GridField is getting a bit of attention design wise very soon to sort out the header and actions, and that has been waiting way too long, likewise though that is only the design and would still require dev prioritisation.

**Comment by robbieaverill** [comment]
That got missed in silverstripe/silverstripe-admin#574, so reopening - here's the last comment from @chillu:

>@clarkepaul suggested that we address the accessibility issues of marking the currently edited page by a differently coloured status icon, see silverstripe/silverstripe-cms#2360

**Comment by newleeland** [comment]
I've tested the following colours to have more contrast with the background of the CMS, while having the enough contrast with blue text

For blue hover background colour can we change:
#ebfbff >> **#dbfbff**

For orange hover background colour can we change:
#ffff2 >> **#fff0e6**
Note. we will also need to change the orange status text (e.g. MODIFIED) to #c93d00 so that this text is also accessible.

**Comment by newleeland** [comment]
### Potential SCSS changes which meet accessibility settings for text
- Lighten CMS bg-color by 4 from #f7f8fa to **#FAFBFC** computed
- orange hover/active bg-color from #fff7f2 to **#FFF2EA**
- blue hover bg-color from #ebfbff to **E8F5FF**
