### ISSUE TITLE
inconsistent use of capitals in labels

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-cms#2361]
# Version:

SS4.3

# Description

URL Segment vs Page name

![image](https://user-images.githubusercontent.com/167154/51010927-4445bf00-15bb-11e9-97e2-bc4819f7dcce.png)

It may pay to have an official policy on for form field labels.  It will make life easier for everyone.

**Comment by ScopeyNZ** [comment]
Thanks for the report @sunnysideup (and your recent drive to point out UX issues!).

This particular issue has actually come up recently and we've implemented a fix in framework for auto-scaffolded labels:

https://github.com/silverstripe/silverstripe-framework/pull/8698

Any other labels that might be manually set will still need to be corrected over time but you can assume our preferred stance is "Sentence case" - ie. only the first letter of the sentence is capitalised.

In some cases there may also be translations that need updating (and/or the text collector run).

If you can point out specific instances in CMS where the labels are still incorrect after pulling in the code provided by the aforementioned PR please feel free to re-open this issue but I'm going to close it for now on the basis that it's fixed by that PR.

Thanks again for the contributions!
