### ISSUE TITLE
SiteTree Search does not display expected results on multiple searches using filters.

### ISSUE THREAD

**Issue by mithungc** [silverstripe/silverstripe-cms#2415]
Scenario -
1. Created a 'Redirector-1' and saved to 'Draft'.
2. Created another 'Redirector-2' and 'Published' it.
3. Utilized the 'SiteTree Search' to show 'Redirector - Page Types'. 
Both 'Redirector 1 & 2' are successfully shown.
4. Attempted another 'Search' to filter only 'Published Pages'.
5. Wrong Search Results are displayed.

**Expected** - Only 'Redirector-2' should be displayed.
Note - Pics attached for reference

Version Tested - 4.3 Demo Version

**Comment by mithungc** [comment]
![Initial Search](https://user-images.githubusercontent.com/28516403/57005564-02558d00-6c2d-11e9-8d83-da1251eaf6b0.JPG)
![Second Search](https://user-images.githubusercontent.com/28516403/57005568-05e91400-6c2d-11e9-86b8-ac688d1989e3.JPG)

**Comment by michalkleiner** [comment]
Seems like the filter is using `OR` instead of `AND` condition.

**Comment by sunnysideup** [comment]
I can confirm that this is still an issue in 4.4 and on that it can also be seen on the demo site:
https://demo.silverstripe.org/admin/pages/?q%5BFilterClass%5D=SilverStripe%5CCMS%5CControllers%5CCMSSiteTreeFilter_PublishedPages&q%5BClassName%5D=SilverStripe%5CErrorPage%5CErrorPage
End-users expect this to be an AND AND search .... e.g. SHow me Product Pages that are Published .... rather than ...  show me Product Pages or Published Pages.

**Comment by adiwidjaja** [comment]
Just found this issue by accident, I think this was solved long ago by #2540, should be closed.
