### ISSUE TITLE
[4.4] Unpublishing pages via batch actions doesn't mark them as draft/modified in the site tree

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-cms#2424]
**SS 4.4.x-dev via CWP 2.3.x-dev**

* Go to pages
* Select Batch actions
* Choose a published page
* Select "Unpublish" from the dropdown
* Click "Go"

The page is unpublished and is no longer visible on the frontend, but it doesn't show an indicator that it is in draft state in the site tree. The state still looks like it's published.

ACs
- After using the site tree batch actions, any action made should be immediately reflected in the site tree

**Comment by emteknetnz** [comment]
Using fresh install of silverstripe/recipe-cms
- Cannot replicate in 4.6.x-dev
- Cannot replicate in 4.4.x-dev

Using fresh install of cwp/cwp-recipe-cms
- Cannot replicate in 2.6.x-dev
- Cannot replicate in 2.3.x-dev

Using fresh install of cwp/cwp-recipe-kitchen-sink
- Cannot replicate in 2.6.x-dev
- Cannot replicate in 2.3.x-dev

Other possibilites
- Slow performance due to large database
- Slow performance due to hosting related e.g. latency with webserver and/or database

Possibly related:
[CWP 2.6.x-dev - site tree performance test](https://github.com/silverstripeltd/product-issues/issues/186)


I cannot replicate this issue so I'm going to close this now
