### ISSUE TITLE
[4.4] Require "optional" GLOBAL_VARIABLES SS_VENDOR_PATH, SS_APP_PATH and SS_THEME_PATH in .env

### ISSUE THREAD

**Issue by SchneiderDe** [silverstripe/silverstripe-cms#2434]
I cannot expose assets from the theme dir in SilverStripe 4.4-rc-1 outside of webroot into webroot. 

In my setup, I have public files under the public_html. Other are one hierarchy outside. Admin is accessible. I installed a theme and made it work. I renamed the directory name of this theme. 

I want to develop a theme with a name of my choice, because I want to suppress internal names of dirs outside of webroot. I cannot do this because soft links breaks, especially for theme and vendor-expose. The assets are not exposed at all. The dir _resources is created outside of webroot and assets in there from my custom directory name for my theme is missing.

A global variable SS_THEME_PATH in .env could be helpful. If found, it could pick up absolute paths of multiple theme directories to be exposed.

**Comment by maxime-rainville** [comment]
Is your public webroot folder called `public_html`. SIlverStripe expects the webroot to be called `public`. If it can't find a `public` folder, it assumes your project root is the web root.

**Comment by SchneiderDe** [comment]
Hi maxime-rainville,

> "SIlverStripe expects the webroot to be called public"

Thats a mistake or a missing feature. Looking at the highest quality of SilverStripe coding skills, this is the last thing I would ever speculate. I created the "public" directory manually. I can expose assets into it. But, your hint solved part of my problem and changed its focus.

I know acrobatics of htaccess and how to manage public_html in parallel to public folder. For variety of reasons, I need public access of index.php mapped to a specific directory, which is configured in httpd.conf. 

Having an extra "public" folder, which would be a deviation from default in httpd.conf, it would remain outside of configured public access as default. Then, many of my administration scripts, like constant permission and ownership checking or even backups shall not function.

While this can be made to work, thats still a missing feature!

It would also mean I must make dramatic changes to httpd.conf to include it through the openbase_dir Directive for it to get redirected. 

While this is possible, this can be better!

So, I am changing this request in the interest of general public and appeal to remove hardcoding of the directory name "public". 

The best solution would be to introduce a new Global Variable in .env: SS_PUBLIC_PATH.

Thus, I have changed the title of this thread.

**Comment by SchneiderDe** [comment]
Hello,

Now I am extending this request, after looking at many things, and am changing the title as follows:

**Require "optional" GLOBAL_VARIABLES SS_VENDOR_PATH, SS_APP_PATH and SS_THEME_PATH in .env.** 

These ones would be absolute. An idea would be to provide directory name of these directories in .env file. This would offer flexibility and security because everything cannot be guessed by a hacker. 

.env may be outside public access and could be additionally secured.

**Comment by dnsl48** [comment]
> SS_VENDOR_PATH

This one cannot be configured in runtime. However, you could amend it in your project specific `composer.json`. Here's an example - https://stackoverflow.com/questions/11883374/how-to-specify-composer-install-path. That's because composer generates autoloader script with the paths included.

> SS_APP_PATH

This one you could also [configure](https://getcomposer.org/doc/04-schema.md#autoload) in the project specific `composer.json`, defining composer autoload paths (e.g. psr-4). That also gets taken into account when autoload scripts being generated.

**Comment by dnsl48** [comment]
> .env may be outside public access and could be additionally secured

Since the 4.1 release we introduced the `public` folder, which should put everything in the root out of reach for webserver and as such `.env` too. The idea would be to put `index.php` with anything else that should be _served_ into the `public` folder, and leave everything else behind.
So, `.env` is outside of public access by default. However, as @maxime-rainville mentioned above, support for serving the project root was left to keep backward compatibility (in case of absence of the `public` folder).

The recommended way is to use `public` folder and set up the server in such a way, that anything before it is not accessible, so even if a hacker knows the names of things, he still cannot access it.

**Comment by ArchitektBerlin** [comment]
Hello dnsl48,

Currently, SilverStripe dicticates on what should be configured in httpd.conf. **Thats a coding blunder.** I proposed to change that. Finally, httpd.conf should determine where the public access of files like index.php should be instead of SilverStripe. 

Since 22 years I manage Multiple Linux servers across continents. I dare not advise anyone, what you did to me. The biggest SilverStripe coding blunder is: " to use public folder and set up the server in such a way". No, my friends, that not how a Linux Administrator thinks. It is the CMS that _HAS_ to follow permissions and environment where it resides.

Regarding composer, I have little experience. So I will try your suggestion later and also try to follw advice given on StackOverflow. Thanks for the hint.

**Comment by robbieaverill** [comment]
I’d note that one reason we suggest it enforce server configuration defaults is because many SilverStripe users are not as accomplished as yourself in server administration.

Recently we made te resources directory name configurable. Making the assets directory configurable would also be beneficial, since both of these folders exist in the public folder. Vendor, app, and themes do not, so are less likely to conflict with CMS defined content, or to provide predictable software discovery routes.

I think I agree that the latter three should be configurable, but I don’t think it would be a high priority for the core team to work on this at the moment for the reasons above. as always, SilverStripe is open source, and we welcome contributions!

I’d also note that a quick glance at Laravel indicates that they don’t support a customisable public folder name either.

**Comment by ArchitektBerlin** [comment]
A location and name of any other directory outside of public root is not an issue at all. 

A gigantic issue crops up the moment SilverStripe demands and commands public root. For what? Thats for no reasons. The only reason is that the directory name is imbibed within the Classes and the Abortion of this name from the pregnant Classes takes time.
That also deviates from the Linux Convention of its Directory hierarchy. It does not leave to in the hands of a coder to determine what and where the public home should reside. 
Conceptually, there is, or cannot be, a practical reason to stick with the idea that CMS should challenge the Linux Environment and determine the name and location of webroot access. 

I must admit that my suggestion of SS_vendor_PATH is wrong.

**Comment by dnsl48** [comment]
> httpd.conf should determine where the public access of files like index.php should be instead of SilverStripe

Agree. However, the `public` folder is merely 1 more level deeper in the project. httpd.conf still completely controls where the project resides and then you may have the `public` folder on top of it (which is the recommended way since 4.1).
On the other hand, even without the name of the public folder being configurable, I was able to use symlinks when I needed more flexibility.

>  I dare not advise anyone, what you did to me.

Sorry, I didn't mean to advise you anything. Merely saying this is the generally recommended way to set it up. It is optional and up to you to decide how you want to deal with it.
On the other hand, this is a collectively made decision in sake of security and is going to be the [only supported way in SilverStripe 5](https://docs.silverstripe.org/en/4/upgrading/upgrading_project/#step).

**Comment by dnsl48** [comment]
> A gigantic issue crops up the moment SilverStripe demands and commands public root. For what? Thats for no reasons. The only reason is that the directory name is imbibed within the Classes and the Abortion of this name from the pregnant Classes takes time.

A agree it needs to be configurable.
I do not believe this is the only reason. The team puts a lot of effort into making things flexible and keep backward compatibility. However, this is not feasible nor possible to always make everything configurable by default. Sometimes the feature needs to be implemented in a rigid way so that it's more stable. Then it may be extended afterwards when we know how it works, what are the pain points and what could be improved.

**Comment by chillu** [comment]
We've got four core committers (@tractorcow @robbieaverill @maxime-rainville and myself) doubting that it's either high priority to fix, or that it's a good idea in the first place (convention over configuration). In a perfect world, everything would be configurable without other tradeoffs (e.g. core development effort required). But in the real world, I don't see us addressing this any time soon. It was discussed as an explicit architecture constraint and tradeoff when implementing the public webroot feature. There are some workarounds discussed here which you could choose to apply. I'll refer to our issue guidelines on https://docs.silverstripe.org/en/4/contributing/issues_and_bugs/

> The bugtracker is not the place to discuss enhancements, please use UserVoice and our community channels. Only log enhancement tickets if they gather a large interest in the community and the enhancement is likely to be implemented in the next couple of months.

In accordance with this, I'm going to close the ticket. I think everyone involved here will be happy to review a pull request if you choose to implement this enhancement.

**Comment by clintLandrum** [comment]
> Recently we made the resources directory name configurable.

@robbieaverill This is great. Thank you. What class is this on? Or could you share a yaml snippet on how to change the resources directory path?

**Comment by kinglozzer** [comment]
@clintLandrum It will be included in the stable `4.4.0` release (or it should be available in `4.4.0-rc1` if you want to test it now): https://docs.silverstripe.org/en/4/changelogs/4.4.0/#adopting-to-new-resources-directory
