### ISSUE TITLE
METAEXTRAHELP Translation in de.yml does not have to be encoded

### ISSUE THREAD

**Issue by MagdalenaM** [silverstripe/silverstripe-cms#2462]
![Screenshot from 2019-08-02 12-41-40](https://user-images.githubusercontent.com/15892304/62364931-14dcac80-b523-11e9-9726-e3b6f8494c30.png)

The translation in german `de.yml` includes HTML-code which is not decoded correct in the CMS. `&lt;` and `&gt;` has to be `<` and `>`. Other translations (`en.yml`) do not encode the angle brackets. So i think there is a mistake in the german translation of `METAEXTRAHELP`.

https://github.com/silverstripe/silverstripe-cms/blob/6a788ca9ed2d4b140653b6e83a5f32c709bc8ea8/lang/de.yml#L208

https://github.com/silverstripe/silverstripe-cms/blob/6a788ca9ed2d4b140653b6e83a5f32c709bc8ea8/lang/en.yml#L218

**Comment by robbieaverill** [comment]
Ideally we'd remove the HTML from the translation string altogether. You can track an issue for doing that here: https://github.com/silverstripe/silverstripe-framework/issues/6537 https://github.com/silverstripe/silverstripe-versioned/issues/188

In the interim, the Transifex translation for German needs to be fixed - this is where the problem is: https://www.transifex.com/silverstripe/silverstripe-cms/viewstrings/#de/master/112005036?q=text%3A'HTML+Tags'

Thanks for raising the issue =)
