### ISSUE TITLE
Preview panel gets displayed over modals in IE11

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-cms#2473]
In IE 11, the preview panel gets displayed over any modal (insert file, insert link, insert media, etc.). This makes impossible to insert files and ruins the UI in other scenarios.

SS4.4 and SS4.5 are affected. SS4.3 is OK.

https://youtu.be/aZFCagCdTzk

![image](https://user-images.githubusercontent.com/1168676/64225498-c2324e00-cf2f-11e9-95bc-8592b6908cea.png)

There's a related but different issue with the Insert Media modal loosing it's background https://github.com/silverstripe/silverstripe-cms/issues/2472

# PR's

- [x] https://github.com/silverstripe/silverstripe-admin/pull/1077

**Comment by Cheddam** [comment]
Note that this is affected by all iframes on the page, including the TinyMCE editor.

I have a solve for the issue: Using `position: absolute` instead of `position: relative` on the top-level Modal element ensures that iframes no longer render above the modal. Unfortunately, the modal is a `reactstrap` component, so I can't just change it directly.

I intend to produce a standalone example of the issue occurring and raise an issue on the `reactstrap` repo to recommend the change based on that.

**Comment by bergice** [comment]
@maxime-rainville can you verify this is still an issue? I can't replicate this on 4.5.

**Comment by emteknetnz** [comment]
Fixed in https://github.com/silverstripe/silverstripe-admin/pull/1077
