### ISSUE TITLE
Issue while installation of Silverstripe CMS version 4.4.4

### ISSUE THREAD

**Issue by prbt2016** [silverstripe/silverstripe-cms#2483]
Hi,

I tried to manually install Silverstripe version on PHP 7.1(Non-SuPHP) , Apache 2.2.34, MYSQL 5.6, Centos 6.4 Final and this is a composer install. However I encountered an issue after entering all the form details. The installation breaks after 'Building database schema step', I encounter the following error : 

```
ERROR [Warning]: chmod(): Operation not permitted IN POST /{{relativeurl}}/{{to}}/{{stripe}}/install.php Line 365 in /{{path}}/{{to}}/{{silverstripe}}/vendor/league/flysystem/src/Adapter/Local.php Source ====== 356: } 357: 358: /** 359: * @inheritdoc 360: */ 361: public function setVisibility($path, $visibility) 362: { 363: $location = $this->applyPathPrefix($path); 364: $type = is_dir($location) ? 'dir' : 'file'; * 365: $success = chmod($location, $this->permissionMap[$type][$visibility]); 366: 367: if ($success === false) { 368: return false; 369: } 370: 371: return compact('path', 'visibility'); Trace ===== chmod(/{{path}}/{{to}}/{{silverstripe}}/public/assets/.htaccess, 436) Local.php:365 League\Flysystem\Adapter\Local->setVisibility(.htaccess, public) AssetAdapter.php:163 SilverStripe\Assets\Flysystem\AssetAdapter->configureServer() AssetAdapter.php:68 SilverStripe\Assets\Flysystem\AssetAdapter->__construct() ReflectionClass->newInstance() InjectionCreator.php:26 SilverStripe\Core\Injector\InjectionCreator->create(SilverStripe\Assets\Flysystem\PublicAssetAdapter, Array) Injector.php:594 SilverStripe\Core\Injector\Injector->instantiate(Array, SilverStripe\Assets\Flysystem\PublicAdapter, singleton) Injector.php:1002 SilverStripe\Core\Injector\Injector->getNamedService(SilverStripe\Assets\Flysystem\PublicAdapter, 1, Array) Injector.php:955 SilverStripe\Core\Injector\Injector->get(SilverStripe\Assets\Flysystem\PublicAdapter) Injector.php:523 SilverStripe\Core\Injector\Injector->convertServiceProperty(%$SilverStripe\Assets\Flysystem\PublicAdapter) Injector.php:515 SilverStripe\Core\Injector\Injector->convertServiceProperty(Array) Injector.php:499 SilverStripe\Core\Injector\Injector->updateSpecConstructor(Array) Injector.php:998 SilverStripe\Core\Injector\Injector->getNamedService(League\Flysystem\Filesystem.public, 1, Array) Injector.php:955 SilverStripe\Core\Injector\Injector->get(League\Flysystem\Filesystem.public) Injector.php:523 SilverStripe\Core\Injector\Injector->convertServiceProperty(%$League\Flysystem\Filesystem.public) Injector.php:650 SilverStripe\Core\Injector\Injector->inject(SilverStripe\Assets\Flysystem\GeneratedAssets, SilverStripe\Assets\Storage\GeneratedAssetHandler) Injector.php:620 SilverStripe\Core\Injector\Injector->instantiate(Array, SilverStripe\Assets\Storage\GeneratedAssetHandler, singleton) Injector.php:1002 SilverStripe\Core\Injector\Injector->getNamedService(SilverStripe\Assets\Storage\GeneratedAssetHandler, 1, Array) Injector.php:955 SilverStripe\Core\Injector\Injector->get(SilverStripe\Assets\Storage\GeneratedAssetHandler) ErrorPage.php:419 SilverStripe\ErrorPage\ErrorPage::get_asset_handler() ErrorPage.php:270 SilverStripe\ErrorPage\ErrorPage->hasStaticPage() ErrorPage.php:167 SilverStripe\ErrorPage\ErrorPage->requireDefaultRecordFixture(Array) ErrorPage.php:140 SilverStripe\ErrorPage\ErrorPage->requireDefaultRecords() DatabaseAdmin.php:382 SilverStripe\ORM\DatabaseAdmin->doBuild(1) Installer.php:176 SilverStripe\Dev\Install\Installer->SilverStripe\Dev\Install\{closure}(SilverStripe\Control\HTTPRequest) call_user_func(Closure, SilverStripe\Control\HTTPRequest) HTTPApplication.php:136 SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest) HTTPMiddlewareAware.php:65 SilverStripe\Control\HTTPApplication->callMiddleware(SilverStripe\Control\HTTPRequest, Closure) HTTPApplication.php:137 SilverStripe\Control\HTTPApplication->execute(SilverStripe\Control\HTTPRequest, Closure, 1) Installer.php:203 SilverStripe\Dev\Install\Installer->install(Array) install5.php:130 include(/{{path}}/{{to}}/{{silverstripe}}/vendor/silverstripe/framework/src/Dev/Install/install5.php) install.php:25 include(/{{path}}/{{to}}/{{silverstripe}}/vendor/silverstripe/framework/src/Dev/Install/install.php) install.php:15 
```

I noticed that the .htaccess in /public/assets/ folder needs ownership of Apache and when i set user for the .htaccess file to Apache , installation works. And when i change ownership to normal 'user' and grant executable permissions(0666), the installer breaks as above.

What causes this issue?. Could you please check this at your end and replicate this issue?. The installer should work with writable permissions for .htaccess in /public/assets/ folder (with normal user and executable permissions.

Awaiting your reply.

**Comment by ScopeyNZ** [comment]
Hi, thanks for taking the time to post to our issue tracker.

This looks like a bit of a general support question - not specifically reporting a bug. 

The issue tracker is reserved for reporting bugs and we don't provide support via the issue tracker. There are great [community support options](http://www.silverstripe.org/community/#introduction) where you can get help including [our forum](https://forum.silverstripe.org), [Stack Overflow (remember to tag as silverstripe)](http://stackoverflow.com/questions/tagged/silverstripe) and even [Slack](http://silverstripe.org/slack).

If you think you've identified a genuine bug please feel free to reply with some more detail about what you consider is the bug. Perhaps use one of the community support options to help work through the issue until there's a clearer idea of what the problem is and whether it's a bug.

Sorry we can't be of more help and good luck resolving your problem!

**Comment by phptek** [comment]
I'd be ken to see this re-opened. I see it all the time in deployments and off the CMS' Security ping. I've been seeing this for years and have just ignored it.

Example:

```
[2021-07-26 17:17:00] error-log.WARNING: E_WARNING: chmod(): Operation not permitted {"code":2,"message":"chmod(): Operation not permitted","file":"/path/to/vendor/league/flysystem/src/Adapter/Local.php","line":368} []
```

As OP says, it's to do with permissions on one or more `.htaccess` files. This is all the more annoying for those of us that don't use Apache and haven't done for years.

**Comment by asecondwill** [comment]
This issue comes up every hour of every day i work with silverstripe.  endless chmod errors on the public/assets/htaccess file and friends.

I'm not on the CWP, so have different requirements than the core mainterners maybe? 

We deploy using beanstalkapp, so it is ssh'd to the server as the user beanstalk, not www-data.  It's a member of the group www-data.  But that isnt enough to avoid these errors.

**Comment by lozcalver** [comment]
@asecondwill it’s been a long while since I encountered this, but from what I recall:

- Don’t commit assets or any of the `.htaccess` files within that directory (you probably aren’t, just noting it in case)
- The best fix is to run any deploy commands (dev/build etc) as the same user that your webserver runs as (`www-data`). That doesn’t necessarily mean SSH'ing in as that user - for example you can use `/etc/sudoers` to allow your `beanstalk` user to run commands as `www-data`
- If that’s not possible, I seem to remember we managed to use `setfacl` once to manage permissions for the assets directory and its contents. I can’t remember any specifics I’m afraid, but it might give you a nudge in the right direction!

**Comment by asecondwill** [comment]
@kinglozzer  - thanks for these suggestions

I am commiting .htaccess files from assets, as they are key parts of the software.  but as a workaround i guess they dont change enough that it would be a problem to not commit them. is that really normal?

i cant change the deploy user, but thank you for the suggestion of using the sudoers and running commands as www-data.  ill try it out.

**Comment by lozcalver** [comment]
> I am commiting .htaccess files from assets, as they are key parts of the software. but as a workaround i guess they dont change enough that it would be a problem to not commit them. is that really normal?

We don’t commit them because they‘re generated on `dev/build` anyway, and we run `dev/build` as part of our deploy process. There’s nothing wrong with committing them, but if you’re seeing permissions issues with those files then it’s possible to keep them out of VCS and generate them on deploy instead

**Comment by asecondwill** [comment]
good point.  thanks
