### ISSUE TITLE
Error:  If there is no parent in RelativeLink()

### ISSUE THREAD

**Issue by amolswnz** [silverstripe/silverstripe-cms#2502]
Silverstripe 4 - If there is no parent in RelativeLink() we get error as 
`[Emergency] Uncaught Error: Call to a member function RelativeLink() on null`

Silverstripe 4
https://github.com/silverstripe/silverstripe-cms/blob/3a028ac1ec8520a8bbb573f488970ecbe383a367/code/Model/SiteTree.php#L648

Silverstripe 3
https://github.com/silverstripe/silverstripe-cms/blob/338c512e154a37936185dd24bf9073c9186f0543/code/model/SiteTree.php#L522

**Comment by dnsl48** [comment]
Hmm. Although we have a check above that tries to ensure (perhaps unsuccessfully) that parent exists:

https://github.com/silverstripe/silverstripe-cms/blob/3a028ac1ec8520a8bbb573f488970ecbe383a367/code/Model/SiteTree.php#L642

That feels to be happening because of some database inconsistencies in your project?
Would you have more details about why ParentID is set, but the parent doesn't exist?

**Comment by amolswnz** [comment]
Yes, you are right. I found inconsistent database records. 
Although here is partial code which triggers the above error
```php
$page = SiteTree::get()->filter('ClassName', 'SomeclassName')->first();

if (!$page) {
    return null;
}
return $page->RelativeLink();
```

**Comment by dnsl48** [comment]
My guess is `$parent = Versioned::get_latest_version(self::class, $this->ParentID);` didn't work there. This might indicate an issue within the Versioned module then?

**Comment by amolswnz** [comment]
Versioned module is good. It's doing its job of returning `null` 
We are assuming `$parent` will be something and we are not checking for it in next line and trying to get `RelativeLink` on this unchecked `$parent`

**Comment by dnsl48** [comment]
Would you like to contribute a PR?
