### ISSUE TITLE
Missing version 4.3.6

### ISSUE THREAD

**Issue by falnyr** [silverstripe/silverstripe-cms#2511]
![image](https://user-images.githubusercontent.com/6673296/72228354-c3c10080-360a-11ea-9352-96abbf9a1772.png)

As the screenshot shows, there seems to be a version 4.3.6 missing.

Is the version 4.3.6 released? More info [here](https://github.com/advisories/GHSA-cg8j-8w52-735v).

**Comment by ScopeyNZ** [comment]
Unfortunately there's no 4.3.6. There are a few minor issues with GitHub's advisory system with PHP - including mentioning non-existing releases for fixes.

**Comment by falnyr** [comment]
Interesting, so even [this post](https://www.silverstripe.org/download/security-releases/CVE-2019-12204) on Silverstripe's website is faulty?

**Comment by ScopeyNZ** [comment]
Okay I did a little more investigation. I assume the fix is actually in the `installer` recipe at version 4.3.6 - but I'm a little out of the loop here. Maybe @chillu can offer some better information?

It seems like currently the release versions of security patches can be confusing with the large number of individual repos/packages we have.

**Comment by robbieaverill** [comment]
Yeah now that patch releases of the components that make up silverstripe-installer are not in lock step with each other, we need to be more specific when publishing security announcements like that. We must include the actual module names that are affected and fixed.
