### ISSUE TITLE
AssetAdmin doSync not work correctly

### ISSUE THREAD

**Issue by bilekt3** [silverstripe/silverstripe-cms#758]
** System: **

- SS 3.1 latest from GIT
- Subsites latest from GIT
- Translatebla latest from GIT 

** What happens: **
When I try to upload file via FTP and click on Sync files - Internal server error is shown. I tried to figure out what it caused and I discovered that in file AssetAdmin.php is code
```php
public function doSync() {
		$message = Filesystem::sync();
		$this->response->addHeader('X-Status', rawurlencode($message));
		
		return;
}
```

This do nothing (fail) but if I change input parameter of method sync to proper ID all folders are synchronized.

When I change folder to leaf level and try it again full sync is evaluated but I think that better way will be pass ID of folder and do small "local" sync to save resources (it is not necessary to always sync all folders).

**Comment by mandrew** [comment]
Just an update to this. Instead of an 'Internal Server Error' which was seen on a previous server environment, I now get a GATEWAY_TIMEOUT error when clicking on the Sync button:

http://.../admin/assets/doSync Failed to load resource: the server responded with a status of 504 (GATEWAY_TIMEOUT)

The sync could still be happening on the server but there doesn't seem to be any checking from the client side to confirm that this is still happening. I'm using "3.1.*@stable". My environment does have a LOT of assets (6 gigs) but this shouldn't really make any difference.

**Comment by micmania1** [comment]
@mandrew You'd get that error when running nginx in front of Apache. The apache process takes too long to respond (longer than nginx timeout). It will usually still keep running in the background but return a gateway timeout.

**Comment by dhensby** [comment]
Closing due to lack of update
