### ISSUE TITLE
CMS admin not loading pages when navigating about

### ISSUE THREAD

**Issue by asecondwill** [silverstripe/silverstripe-cms#826]
When clicking between screens "pages", "Files", "Comments" etc the page is not loaded for some users some of the time.  No JS error is raised in console.  The ajax response is being returned with correct looking html and a 200 code but the view isn't being refreshed. 

Iv'e checked the usual suspects  whitespace in mysite code files, dev/build?flush=all   to no avail.

**Comment by MrJamesEllis** [comment]
Similar prob but different solution for me and this issue is coming up in searches for related terms so I thought I'd add one solution to avoid over-googling.

If you are having problems with admin screens not loading, it may be due to the size of the GridField being returned. In Chrome, I had 200 OK responses and no errors but no relevant GridField of records showing for the request. e.g I could click ModelAdmin tabs, the URL would change but the content loaded wouldn't. This was on a local dev slot as well so network wasn't the issue.

Changing the GridField page_length from 30 to 10 helped out (fixed it), which may point to a browser setting related to the maximum content length or similar.

In yr yaml :

ModelAdmin:
  page_length: 10


hope that helps.
