### ISSUE TITLE
In Silverstripe 3.1.2 I get a "Forbidden" when trying to upload a file

### ISSUE THREAD

**Issue by evjan** [silverstripe/silverstripe-cms#933]
When running the same site on 3.0.5, uploads work just fine.

![07c8b37c-f931-11e2-8814-3549de9dc0b4](https://f.cloud.github.com/assets/18362/2123994/dad8f864-9236-11e3-841b-d60deabbd91a.png)

**Comment by cwchong** [comment]
Sorry for the necromancy; although this has been closed, i have recently encountered the similar issue on 3.1.12 installation, which had been working fine until recently (not sure what the host did either), and managed to find the cause and solution, so leaving here for posterity after some mind boggling debugging.

**Symptoms**
When you inspect the network and find that "/admin/assets/add/EditForm/field/AssetUploadField/fileexists?filename=yourfile.jpg" is returning 403 "Not logged in", try visiting the following URLs directly in your browser (after logged in)

/admin/assets/add/EditForm/field/AssetUploadField/fileexists?filename=yourfile
and
/admin/assets/add/EditForm/field/AssetUploadField/fileexists?filename=yourfile.jpg
and
/admin/assets/add/EditForm/field/AssetUploadField/fileexists?filename=yourfile.jpg&

If the first URL works (returning jason message like {"exists":false}), and the second URL throws you directly back to login form (even though you have logged in), and the third URL works, then it might be the case where the server (most likely misconfigured?) somehow thinks that the second URL is pointing to a file, because of the ".jpg" ending (not sure if this is an htaccess issue though).

**Solution**
Look for framework/javascript/Upload.js:
`_onSend: function (e, data) {
			...
			if (config.overwriteWarning) {
				$.get(
					config['urlFileExists'],
					{'filename': data.files[0].name**, 'pad': 1**}, // approx line 66
					...
`
adding in the bolded part. All it does is to add some dummy variable so that the fileexists xhr call becomes
/admin/assets/add/EditForm/field/AssetUploadField/fileexists?filename=yourfile.jpg&pad=1

The server should route the request correctly then.

Not sure if this is a server configuration or SS issue, but hopefully this helps someone else.
