### ISSUE TITLE
asset admin upload field - folder is always  "/" in fileexists check

### ISSUE THREAD

**Issue by sheadawson** [silverstripe/silverstripe-cms#950]
When the upload field in asset admin fires off it's ajax request to check if the file already exists, (admin/assets/add/EditForm/field/AssetUploadField/fileexists), it doesn't pass on any information about what folder the file is attempting to be uploaded to, so the folder that the fileexists check checks against is always "/".

Other upload fields are fine but CMSFileAddController relies on the presence of a get param $ID  to know what folder the file is being uploaded to.

**Comment by dio5** [comment]
This seems to be broken again in at least in 3.4.1. The fix is not there anymore either - I'm assuming some other bits must have changed.

**Comment by dhensby** [comment]
@dio5 are you prepared to provide a patch?

**Comment by dhensby** [comment]
FYI It was broken here: https://github.com/silverstripe/silverstripe-cms/pull/1566

We stopped using sessions to store the current page state, I think?

**Comment by dio5** [comment]
Yeah I literally just reverted the CMSFileAddController which seems to do the trick... I know that breaks the 1566 issue, but I don't see that being a problem for us at the moment.

**Comment by dhensby** [comment]
@jonom your PR broke this again - are you able to look into a fix?

**Comment by jonom** [comment]
@dhensby sorry which PR?

**Comment by jonom** [comment]
Oh I see it now, I'll take a look

**Comment by jonom** [comment]
Sorry about the regression, I wasn't aware you could opt-in to overwriting files so I hadn't encountered this issue before. Replicated the issue with following config

```yml
UploadField:
  overwriteWarning: true
Upload:
  replaceFile: true
```

This issue only affects the upload field in the asset admin area, and only if `overwriteWarning` is enabled. It's also a Framework problem rather than CMS.

I don't want to add back the reliance on Session storage if we can help it as I think it's a bad design pattern. Example: I often want to have two CMS windows open at once to speed up my productivity and Session data can cross contaminate between windows. We shouldn't have to rely on a Session variable to make something like this work, the ajax request should include all the necessary information.

The fix I came up with (https://github.com/jonom/silverstripe-framework/commit/da566c5b696fc96c6cc1d92634c7ccae2526102e) unfortunately modifies an API by adding an optional parameter, but it's the cleanest way I could see to fix it. Perhaps in a case like this it's better to make a SemVer exception than hack in an ugly solution we wouldn't want to maintain? Or maybe I should just push a fix to 3 branch?

Side note, a static File::checkExists($filename, $relativePath) function might be more useful than a protected equivalent on UploadField?

**Comment by dhensby** [comment]
> Or maybe I should just push a fix to 3 branch?

yep

> Side note, a static File::checkExists($filename, $relativePath) function might be more useful than a protected equivalent on UploadField?

also agreed - but that kind of already exists, I would have thought?

**Comment by jonom** [comment]
@dhensby there is a File::find() method which works a little differently but should be okay, have used that in alternate solution: https://github.com/silverstripe/silverstripe-framework/pull/6433

**Comment by chillu** [comment]
That class has been removed in 4.x, replaced with a leaner and rewritten `UploadField`, which no longer performs this `fileexists` check via ajax
